import { describe, expect, it } from 'vitest';
import { ErrorCodes } from '../../../src/output/error-codes.js';

const DD_ERROR_NAMES = [
  'DD_DOCUMENT_INVALID',
  'DD_SCHEMA_UNRESOLVABLE',
  'DD_SCHEMA_SHAPE_INVALID',
  'DD_ID_INVALID',
  'DD_ID_DUPLICATE',
  'DD_ADDRESS_INVALID',
  'DD_LINK_TYPE_MISMATCH',
  'DD_ENUM_INVALID',
  'DD_STATE_NOTE_REQUIRED',
  'DD_HUMAN_SKIP_RECEIPT_REQUIRED',
  'DD_SCHEMA_NOT_FOUND',
  'DD_SCHEMA_PACKAGE_INVALID',
  'DD_SCHEMA_NAME_CONFLICT',
  'DD_SCHEMA_SHADOWED',
  'DD_SCHEMA_VERSION_UNSUPPORTED',
  'DD_SCHEMA_ENUM_INVALID',
  'DD_SCHEMA_SCAN_FAILED',
  'DD_SCHEMA_PATH_ESCAPE',
  'DD_SCHEMA_WRITE_FAILED',
  'DD_DOCS_ENTRY_NOT_FOUND',
  'DD_RENDER_FAILED',
  'DD_RENDER_WRITE_FAILED',
  'DD_RENDER_DRIFT',
  'DD_ADAPTER_NOT_FOUND',
  'DD_ADAPTER_LOAD_FAILED',
  'DD_ADAPTER_RUNTIME_FAILED',
  'DD_ADAPTER_OUTPUT_INVALID',
  'DD_LIVE_BASIS_REFRESH_FAILED',
  'DD_WATCH_FAILED',
  'DD_BUILD_INPUT_INVALID',
  'DD_LINK_UNRESOLVED',
  'DD_LINK_TARGET_MISSING',
  'DD_LINK_TARGET_UNTRACKED',
  'DD_LINK_PATH_ESCAPE',
  'DD_BASIS_STALE',
  'DD_BASIS_VERIFY_FAILED',
  'DD_LINK_SCAN_FAILED',
  'DD_GRAPH_FAILED',
  'DD_DOCTOR_FINDINGS',
  'DD_DOCTOR_SCAN_FAILED',
  'DD_GATE_UNSATISFIED',
  'DD_GATE_TARGET_INVALID',
  'DD_GATE_SCHEMA_UNRESOLVABLE',
  'DD_GATE_BASIS_STALE',
  'DD_GATE_EVALUATION_FAILED',
  'DD_GATE_OVERRIDE_INVALID',
  'DD_GATE_STATE_INVALID',
  'DD_GATE_EVENT_WRITE_FAILED',
  'DD_GATE_SURFACE_FAILED',
  'DD_GATE_LINK_MISSING',
] as const;

describe('dd E400-E449 freeze', () => {
  it('allocates every code exactly once with its final stable name', () => {
    const values = DD_ERROR_NAMES.map((name) => ErrorCodes[name]);
    expect(values).toEqual(Array.from({ length: 50 }, (_, index) => `E${400 + index}`));
    expect(new Set(values).size).toBe(50);
  });
});
