import type { DdDoc } from '@ai-substrate/dd';
import { Command } from 'commander';
import { describe, expect, it } from 'vitest';
import {
  registerBuilderCommandContract,
  resolveBuilderDispatchKind,
} from '../../src/services/builder/commands.js';
import {
  builderContext,
  isBuilderPreservationExcluded,
  readBuilderDocument,
  readBuilderRecord,
  runBuilderCheck,
  sameBuilderDocumentIntent,
  sha256,
  writeBuilderDocument,
  writeBuilderRecord,
} from '../../src/services/builder/records.js';
import type { AllocationRecord, BuilderRecord } from '../../src/services/builder/types.js';
import {
  BUILDER_FIXTURE_GUIDE,
  BUILDER_FIXTURE_PLAN,
  builderFixture,
  fixtureAck,
  fixtureAllocation,
  fixtureBaseline,
  fixtureComposition,
  fixtureDispatch,
  fixturePacket,
  fixturePreservation,
  fixtureReview,
} from '../fixtures/builder-contracts.js';

const target = '/repo/docs/plans/001-example/assets/team/allocation.dd.json';

describe('Builder shared DD record contract', () => {
  it.each([
    fixtureAllocation(),
    fixtureBaseline(),
    fixturePacket(),
    fixtureAck(),
    fixtureDispatch(),
    fixtureComposition(),
    fixtureReview(),
    fixturePreservation(),
  ])('round-trips the $record_type boundary through the real DD schema and renderer', (value: BuilderRecord) => {
    const { deps, fs } = builderFixture();
    const path = `/repo/records/${value.record_type}.dd.json`;
    const saved = writeBuilderRecord(deps, path, value);
    expect(saved.ok).toBe(true);
    expect(readBuilderRecord(deps, path, value.record_type)).toEqual(saved);
    expect(fs.readText(path.replace('.json', '.md'))).toContain('GENERATED by `ddocs build`');
    const source = fs.readText(path);
    if (source === null) throw new Error('The successful record write did not create its source.');
    if (saved.ok) expect(saved.value.ref.sha256).toBe(sha256(source));
  });

  it('rejects unknown review verdicts and role-setting provenance at the DD boundary', () => {
    const { deps, fs } = builderFixture();
    const review = fixtureReview();
    Reflect.set(review, 'verdict', 'approved-ish');
    expect(writeBuilderRecord(deps, '/repo/review.dd.json', review)).toMatchObject({
      ok: false,
      code: 'E470',
    });
    const packet = fixturePacket();
    Reflect.set(packet.requested.source, 'model', 'invented');
    expect(writeBuilderRecord(deps, '/repo/packet.dd.json', packet)).toMatchObject({
      ok: false,
      code: 'E470',
    });
    expect(fs.exists('/repo/review.dd.json')).toBe(false);
    expect(fs.exists('/repo/packet.dd.json')).toBe(false);
  });

  it('reads the canonical guide without confusing the product plan schema', () => {
    const { deps } = builderFixture();
    expect(readBuilderDocument(deps, BUILDER_FIXTURE_GUIDE, 'builder/impl-guide').ok).toBe(true);
    expect(readBuilderDocument(deps, BUILDER_FIXTURE_GUIDE, 'builder/plan')).toMatchObject({
      ok: false,
      code: 'E470',
    });
  });

  it('preserves the distinction between external ownership and clone isolation', () => {
    const { deps } = builderFixture();
    const value = fixtureAllocation({ owner: 'external', kind: 'clone' });
    expect(writeBuilderRecord(deps, target, value).ok).toBe(true);
    expect(readBuilderRecord<AllocationRecord>(deps, target, 'allocation')).toMatchObject({
      ok: true,
      value: { value: { owner: 'external', kind: 'clone' } },
    });
  });

  it('rejects malformed records before creating any source or lock', () => {
    const { deps, fs } = builderFixture();
    const value = fixtureAllocation();
    Reflect.deleteProperty(value, 'root');
    expect(writeBuilderRecord(deps, target, value)).toMatchObject({ ok: false, code: 'E470' });
    expect(fs.exists(target)).toBe(false);
    expect(fs.exists(`${target}.lock`)).toBe(false);
  });

  it('requires the current source digest for a changed record and supports identical retries', () => {
    const { deps, fs } = builderFixture();
    const value = fixtureAllocation();
    const initial = writeBuilderRecord(deps, target, value);
    expect(initial.ok).toBe(true);
    if (!initial.ok) throw new Error(initial.message);
    expect(writeBuilderRecord(deps, target, value).ok).toBe(true);
    const changed = { ...value, journal: [...value.journal, 'preserved'] };
    expect(writeBuilderRecord(deps, target, changed)).toMatchObject({ ok: false, code: 'E472' });
    expect(
      writeBuilderRecord(deps, target, changed, { expectedSha256: '0'.repeat(64) }),
    ).toMatchObject({ ok: false, code: 'E472' });
    expect(readBuilderRecord(deps, target, 'allocation')).toEqual(initial);
    expect(
      writeBuilderRecord(deps, target, changed, { expectedSha256: initial.value.ref.sha256 }).ok,
    ).toBe(true);
    expect(fs.exists(`${target}.lock`)).toBe(false);
  });

  it('does not remove an existing writer lock or a foreign temporary file', () => {
    const held = builderFixture({ [`${target}.lock`]: 'other-writer' });
    expect(writeBuilderRecord(held.deps, target, fixtureAllocation())).toMatchObject({
      ok: false,
      code: 'E472',
    });
    expect(held.fs.readText(`${target}.lock`)).toBe('other-writer');
    const collision = builderFixture({ [`${target}.nonce-1.tmp`]: 'foreign bytes' });
    expect(writeBuilderRecord(collision.deps, target, fixtureAllocation())).toMatchObject({
      ok: false,
      code: 'E472',
    });
    expect(collision.fs.readText(`${target}.nonce-1.tmp`)).toBe('foreign bytes');
    expect(collision.fs.exists(target)).toBe(false);
  });

  it('keeps the original source when publication fails', () => {
    const { deps, fs } = builderFixture();
    const saved = writeBuilderRecord(deps, target, fixtureAllocation());
    if (!saved.ok) throw new Error(saved.message);
    fs.failRenames.add(`${target}.nonce-2.tmp`);
    expect(
      writeBuilderRecord(deps, target, fixtureAllocation({ journal: ['changed'] }), {
        expectedSha256: saved.value.ref.sha256,
      }),
    ).toMatchObject({ ok: false, details: { source_written: false } });
    expect(readBuilderRecord(deps, target, 'allocation')).toEqual(saved);
    expect(fs.exists(`${target}.lock`)).toBe(false);
  });

  it('reports a committed source when only derived-face publication fails', () => {
    const { deps, fs } = builderFixture();
    fs.failRenames.add(`${target.replace('.json', '.md')}.nonce-1.tmp`);
    const result = writeBuilderRecord(deps, target, fixtureAllocation());
    expect(result).toMatchObject({ ok: false, details: { source_written: true } });
    expect(readBuilderRecord(deps, target, 'allocation').ok).toBe(true);
    if (!result.ok) expect(result.next_action).toContain('ddocs build');
  });

  it('refuses source symlinks and writes outside an explicit root', () => {
    const { deps, fs } = builderFixture({ [target]: '{}' });
    fs.symlinkPaths.add(target);
    expect(readBuilderRecord(deps, target, 'allocation').ok).toBe(false);
    expect(
      writeBuilderRecord(deps, '/elsewhere/allocation.dd.json', fixtureAllocation()),
    ).toMatchObject({ ok: false, code: 'E477' });
    expect(fs.exists('/elsewhere/allocation.dd.json')).toBe(false);
  });

  it('resolves generated plan faces to their canonical source and rejects repository escape', () => {
    const { deps } = builderFixture();
    expect(builderContext(deps, BUILDER_FIXTURE_PLAN.replace('.json', '.md'))).toMatchObject({
      ok: true,
      value: { planPath: `/repo/${BUILDER_FIXTURE_PLAN}` },
    });
    expect(builderContext(deps, '../outside')).toMatchObject({ ok: false, code: 'E470' });
  });

  it('preserves omitted effort rather than manufacturing observed effort', () => {
    const { deps } = builderFixture();
    const packet = fixturePacket();
    const path = '/repo/packet.dd.json';
    expect(writeBuilderRecord(deps, path, packet).ok).toBe(true);
    const loaded = readBuilderRecord(deps, path, 'packet');
    if (!loaded.ok) throw new Error(loaded.message);
    expect((loaded.value.value as typeof packet).requested).not.toHaveProperty('effort');
  });
});

describe('Builder executable checks', () => {
  it('passes literal argv, cwd and timeout through the existing exec port and retains failures', async () => {
    const { deps, exec } = builderFixture(
      {},
      { node: { code: 7, stdout: 'partial', stderr: 'failure' } },
    );
    const args = ['check.mjs', 'value; touch forbidden', 'space separated'];
    const result = await runBuilderCheck(deps, {
      id: 'vd-0001',
      description: 'Boundary proof',
      command: 'node',
      args,
      cwd: 'test',
      timeout_ms: 700,
    });
    expect(exec.calls).toEqual([{ command: 'node', args, cwd: '/repo/test', timeoutMs: 700 }]);
    expect(result).toMatchObject({
      ok: true,
      value: { exit_code: 7, stdout: 'partial', stderr: 'failure' },
    });
  });
  it('refuses an escaping cwd before executing anything', async () => {
    const { deps, exec } = builderFixture();
    expect(
      await runBuilderCheck(deps, {
        id: 'vd-0001',
        description: 'Invalid',
        command: 'node',
        args: [],
        cwd: '../outside',
        timeout_ms: 1,
      }),
    ).toMatchObject({ ok: false, code: 'E470' });
    expect(exec.calls).toEqual([]);
  });
  it('records a timeout as failed execution rather than successful proof', async () => {
    const { deps, exec } = builderFixture({}, { node: { code: 0, hang: true } });
    expect(
      await runBuilderCheck(deps, {
        id: 'vd-0001',
        description: 'Timeout',
        command: 'node',
        args: [],
        cwd: '.',
        timeout_ms: 10,
      }),
    ).toMatchObject({ ok: true, value: { exit_code: 124 } });
    expect(exec.kills).toHaveLength(1);
  });
});

function parser() {
  const calls: Array<{ verb: string; argument: string; options: Record<string, unknown> }> = [];
  const program = new Command()
    .exitOverride()
    .configureOutput({ writeErr: () => undefined, writeOut: () => undefined });
  registerBuilderCommandContract(program, (verb, argument, options) => {
    calls.push({ verb, argument, options });
  });
  return {
    calls,
    parse: (args: string[]) => program.parseAsync(['builder', ...args], { from: 'user' }),
  };
}

describe('Builder public command grammar', () => {
  it('parses the advertised defaults without inventing actor or workspace', async () => {
    const { calls, parse } = parser();
    await parse(['new', 'example', '--workspace', '/workers/new root', '--actor', 'peer-pm']);
    expect(calls).toEqual([
      {
        verb: 'new',
        argument: 'example',
        options: {
          workspace: '/workers/new root',
          actor: 'peer-pm',
          kind: 'worktree',
          base: 'HEAD',
          phase: ['Implementation'],
        },
      },
    ]);
  });
  it.each([
    ['new', 'example'],
    ['adopt', 'plan', '--actor', 'pm', '--owner', 'harness'],
    ['guide', 'plan', '--init', '--check'],
    ['contracts', 'plan', '--seal'],
    ['settings', 'plan', '--model', 'provider/model'],
    ['compose', 'plan'],
    ['compose', 'plan', '--import', 'units.json', '--verify', 'abc'],
    ['advance', 'plan', '--now', 'phase-1', '--force'],
    ['tidy', 'allocation.dd.json'],
  ])('refuses incomplete, conflicting or unsafe arguments: %j', async (...args) => {
    const { calls, parse } = parser();
    await expect(parse(args)).rejects.toThrow();
    expect(calls).toEqual([]);
  });
  it('passes declared dispatch overrides verbatim and leaves effort absent', async () => {
    const { calls, parse } = parser();
    await parse([
      'dispatch',
      'plan',
      '--unit',
      'tk-0002',
      '--workspace',
      '/workers/one',
      '--parent',
      'pm',
      '--model',
      'provider/model',
    ]);
    expect(calls[0]).toMatchObject({
      verb: 'dispatch',
      options: {
        unit: 'tk-0002',
        workspace: '/workers/one',
        parent: 'pm',
        model: 'provider/model',
        kind: 'guide',
      },
    });
    expect(calls[0]?.options).not.toHaveProperty('effort');
  });
});

describe('Builder dispatch kind resolution', () => {
  it.each([
    ['clone-per-coder', 'guide', 'clone'],
    ['worktree-per-coder', 'guide', 'worktree'],
    ['clone-per-coder', 'worktree', 'worktree'],
    ['worktree-per-coder', 'clone', 'clone'],
  ] as const)('resolves %s with selector %s to %s', (mode, selection, kind) => {
    expect(resolveBuilderDispatchKind(mode, selection)).toEqual({ ok: true, value: kind });
  });

  it.each([
    'guide',
    'clone',
    'worktree',
  ] as const)('refuses a solo guide even with selector %s', (selection) => {
    expect(resolveBuilderDispatchKind('solo', selection)).toMatchObject({
      ok: false,
      code: 'E471',
      next_action: expect.any(String),
    });
  });

  it('does not turn malformed mode or selector input into a plausible worktree', () => {
    expect(resolveBuilderDispatchKind('unknown' as never, 'clone')).toMatchObject({
      ok: false,
      code: 'E470',
    });
    expect(resolveBuilderDispatchKind('clone-per-coder', 'unknown' as never)).toMatchObject({
      ok: false,
      code: 'E470',
    });
  });
});

function intentDocument(schema: string, values: Record<string, unknown>): DdDoc {
  return {
    dd: { schema },
    sections: Object.entries(values).map(([name, value]) => ({ name, value })),
    references: [],
  };
}

describe('Builder historical intent comparison', () => {
  it('ignores only recorded progress on recognised plan rows', () => {
    const before = intentDocument('builder/plan', {
      meta: { title: 'Example', status: 'draft' },
      acceptance_criteria: [{ id: 'ac-0001', text: 'Preserve work', state: 'unchecked' }],
      phases: [{ id: 'ph-0001', title: 'Implementation', state: 'unchecked' }],
      tasks: [{ id: 'tk-0001', title: 'Implement', state: 'unchecked' }],
      done_when: { 'tk-0001': [{ id: 'dw-0001', text: 'Proof exists', state: 'unchecked' }] },
    });
    const after = intentDocument('builder/plan', {
      meta: { status: 'complete', title: 'Example' },
      acceptance_criteria: [
        { id: 'ac-0001', text: 'Preserve work', state: 'checked', proven_by: 'proof.json' },
      ],
      phases: [
        { id: 'ph-0001', title: 'Implementation', state: 'checked', proven_by: 'proof.json' },
      ],
      tasks: [{ id: 'tk-0001', title: 'Implement', state: 'checked', proven_by: 'proof.json' }],
      done_when: {
        'tk-0001': [
          { id: 'dw-0001', text: 'Proof exists', state: 'checked', proven_by: 'proof.json' },
        ],
      },
    });
    expect(sameBuilderDocumentIntent(before, after, '001-example')).toBe(true);
    (after.sections[1].value as Array<Record<string, unknown>>)[0].text = 'Discard work';
    expect(sameBuilderDocumentIntent(before, after, '001-example')).toBe(false);
  });

  it('does not erase state-like fields outside recognised progress rows', () => {
    for (const section of ['meta', 'tasks']) {
      const before = intentDocument('builder/plan', {
        [section]: { state: 'required', proven_by: 'a.json' },
      });
      const after = intentDocument('builder/plan', {
        [section]: { state: 'optional', proven_by: 'b.json' },
      });
      expect(sameBuilderDocumentIntent(before, after, '001-example')).toBe(false);
    }
  });

  it('ignores guide update timestamps but retains baseline and unit intent', () => {
    const before = intentDocument('builder/impl-guide', {
      meta: { title: 'Example', updated: '2026-09-04' },
      baseline: { receipt: 'team/baseline.dd.json' },
      units: [{ id: 'tk-0001', paths: ['src/a.ts'], model: 'provider/coder' }],
    });
    const after = structuredClone(before);
    (after.sections[0].value as Record<string, unknown>).updated = '2026-09-05';
    expect(sameBuilderDocumentIntent(before, after, '001-example')).toBe(true);
    (after.sections[1].value as Record<string, unknown>).receipt = 'team/baseline-v2.dd.json';
    expect(sameBuilderDocumentIntent(before, after, '001-example')).toBe(false);
    after.sections[1] = structuredClone(before.sections[1]);
    (after.sections[2].value as Array<Record<string, unknown>>)[0].paths = ['src/b.ts'];
    expect(sameBuilderDocumentIntent(before, after, '001-example')).toBe(false);
  });

  it('normalises same-plan DD archive addresses, not prose or a different plan', () => {
    const before = intentDocument('builder/impl-guide', {
      meta: { plan: 'docs/plans/001-example/plan.dd.json#meta' },
      baseline: { receipt: 'docs/plans/001-example/assets/team/baseline.dd.json' },
    });
    const after = intentDocument('builder/impl-guide', {
      meta: { plan: 'docs/plans/archive/001-example/plan.dd.json#meta' },
      baseline: { receipt: 'docs/plans/archive/001-example/assets/team/baseline.dd.json' },
    });
    expect(sameBuilderDocumentIntent(before, after, '001-example')).toBe(true);
    expect(sameBuilderDocumentIntent(before, after, '002-other')).toBe(false);
    const textBefore = intentDocument('builder/plan', {
      summary: 'Use docs/plans/001-example/plan.dd.json#meta here',
    });
    const textAfter = intentDocument('builder/plan', {
      summary: 'Use docs/plans/archive/001-example/plan.dd.json#meta here',
    });
    expect(sameBuilderDocumentIntent(textBefore, textAfter, '001-example')).toBe(false);
  });

  it('does not rewrite URLs, unproven relative relocations, or external roots', () => {
    for (const [left, right] of [
      [
        'https://example.test/docs/plans/001-example/plan.dd.json#meta',
        'https://example.test/docs/plans/archive/001-example/plan.dd.json#meta',
      ],
      ['../../002-other/plan.dd.json#meta', '../../../002-other/plan.dd.json#meta'],
      [
        '/a/docs/plans/001-example/plan.dd.json#meta',
        '/b/docs/plans/archive/001-example/plan.dd.json#meta',
      ],
      [
        '/external/docs/plans/001-example/plan.dd.json#meta',
        '/external/docs/plans/archive/001-example/plan.dd.json#meta',
      ],
      [
        'docs/plans/001-example/../../other.dd.json#meta',
        'docs/plans/archive/001-example/../../other.dd.json#meta',
      ],
      [
        'nested/docs/plans/001-example/plan.dd.json#meta',
        'nested/docs/plans/archive/001-example/plan.dd.json#meta',
      ],
      [
        'docs/plans/001-example-more/plan.dd.json#meta',
        'docs/plans/archive/001-example-more/plan.dd.json#meta',
      ],
    ]) {
      expect(
        sameBuilderDocumentIntent(
          intentDocument('builder/plan', { summary: left }),
          intentDocument('builder/plan', { summary: right }),
          '001-example',
        ),
      ).toBe(false);
    }
  });

  it.each([
    '-v2',
    '-old',
    '-backup',
    '-archive',
  ])('does not alias the sibling plan suffix %s', (suffix) => {
    const before = intentDocument('builder/plan', {
      meta: { plan: `docs/plans/001-example${suffix}/plan.dd.json#meta` },
    });
    const after = intentDocument('builder/plan', {
      meta: { plan: `docs/plans/archive/001-example${suffix}/plan.dd.json#meta` },
    });
    expect(sameBuilderDocumentIntent(before, after, '001-example')).toBe(false);
  });

  it('refuses unknown schemas, mismatched schemas and unsafe plan identities', () => {
    const plan = intentDocument('builder/plan', { meta: { title: 'Example' } });
    const guide = intentDocument('builder/impl-guide', { meta: { title: 'Example' } });
    const other = intentDocument('builder/team', { meta: { title: 'Example' } });
    expect(sameBuilderDocumentIntent(plan, guide, '001-example')).toBe(false);
    expect(sameBuilderDocumentIntent(other, other, '001-example')).toBe(false);
    expect(sameBuilderDocumentIntent(plan, plan, '../001-example')).toBe(false);
  });
});

describe('Builder preservation inventory policy', () => {
  it.each([
    '.git',
    '.git/objects/a',
    'node_modules/pkg/index.js',
    'nested/node_modules/pkg/file',
    '.venv/lib/package.py',
    '__pycache__/module.pyc',
    '.cache/runtime.bin',
    '.vite/deps/file.js',
  ])('recognises the dependency/runtime path %s', (path) => {
    expect(isBuilderPreservationExcluded(path)).toBe(true);
  });

  it.each([
    'dist/report.pdf',
    'build/diagram.svg',
    'output/result.json',
    'scratch/proof.json',
    'reports/cache.json',
    'cache/report.json',
    'unknown/file.bin',
    '.gitignore',
    'node_modules-notes/decision.txt',
    '.cache-backup/proof.json',
    'Node_Modules/file',
    'docs/plans/001-example/assets/report.json',
    '/node_modules/file',
    'C:/node_modules/file',
    'node_modules/../report.json',
    './node_modules/file',
    'nested//node_modules/file',
    'nested\\node_modules\\pkg\\file',
    'node_modules/file\0suffix',
    '',
  ])('keeps unknown and work-product paths required: %s', (path) => {
    expect(isBuilderPreservationExcluded(path)).toBe(false);
  });
});

describe('Builder bootstrap document writes', () => {
  it('writes a backpressure draft and links the canonical plan through the validated writer', () => {
    const { deps, fs } = builderFixture();
    const pressurePath = '/repo/docs/plans/001-example/assets/backpressure.dd.json';
    const pressure = JSON.parse(
      fs.readText('/package/templates/backpressure.template.json') ?? 'null',
    ) as DdDoc;
    const pressureWrite = writeBuilderDocument(deps, pressurePath, pressure);
    expect(pressureWrite.ok).toBe(true);
    expect(fs.readText(pressurePath.replace('.dd.json', '.dd.md'))).toContain(
      'GENERATED by `ddocs build`',
    );
    const planRead = readBuilderDocument(deps, BUILDER_FIXTURE_PLAN, 'builder/plan');
    if (!planRead.ok) throw new Error(planRead.message);
    const plan = planRead.value.value;
    const meta = plan.sections.find((section) => section.name === 'meta')?.value as Record<
      string,
      unknown
    >;
    meta.backpressure = 'assets/backpressure.dd.json#meta';
    const planWrite = writeBuilderDocument(deps, BUILDER_FIXTURE_PLAN, plan, {
      expectedSha256: planRead.value.ref.sha256,
    });
    expect(planWrite.ok).toBe(true);
  });
});
