import { type DdAddress, isAddressFailure, parseAddress } from '../core/address.js';
import { DEFAULT_GATE_TERMINAL_STATES } from '../core/constants.js';
import { type DdDerivedState, deriveState } from '../core/derive.js';
import type { DdDoc, DdSection, DdShape, ResolvedDdSchema } from '../core/model.js';
import { isRecord } from '../core/value.js';
import type { DdAdapterContext, DdRenderContext } from './contract.js';

/**
 * How deep a nested container renders inside a table cell before it collapses to
 * `⟨…⟩`. THE one limit this renderer invents, so it ships as a named constant with
 * a ruling and a fixture that crosses it (P2 DL-006): `limits.dd.json` carries one
 * row sitting at the bound and one going past it.
 *
 * Two levels is the readable ceiling for a markdown cell — a third turns the row
 * into a wall of punctuation, and the full value is one `jq` away in the `.dd.json`
 * that is the source of truth anyway.
 */
export const MAX_CELL_DEPTH = 2;

/** The generated-file banner. Byte-identical in every render; the drift gate keys off it. */
export const RENDER_BANNER =
  '<!-- GENERATED by `harness dd build` — do not hand-edit; regenerate from the .dd.json. -->';

/** Placeholder for a value that is simply not there. */
const EMPTY_CELL = '—';

/** Types the renderer knows itself; anything else is a custom type and needs an adapter. */
const BUILTIN_TYPES = new Set([
  'array',
  'bool',
  'enum',
  'int',
  'link',
  'number',
  'object',
  'state',
  'string',
  'text',
]);

/**
 * Gate marks in the markdown task-list vocabulary a plan reader already knows:
 * passes / holds / blocked. A mark PREFIXES the state word, never replaces it —
 * a schema may declare its own state vocabulary (workshop-002 Ruling 2), so
 * `shipped`, `waived` and `approved` must stay distinguishable at a glance
 * instead of collapsing into one identical `[x]`.
 */
const PIP_TERMINAL = '[x]';
const PIP_HOLDS = '[ ]';
const PIP_BLOCKED = '[-]';
/** Partial progress, per plan § 3.1 (`[~] 3/5`). */
const PIP_PARTIAL = '[~]';

function basename(path: string): string {
  const parts = path.replaceAll('\\', '/').split('/');
  return parts[parts.length - 1] ?? path;
}

/** GitHub-style heading slug — the only anchor form, per workshop-001 § Anchors. */
export function headingSlug(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/** Table-cell escaping: a cell may never break the row, and may never inject HTML. */
function escapeCell(text: string): string {
  return text
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\|/g, '\\|')
    .replace(/\r\n|\r|\n/g, '<br>');
}

function isBlank(value: unknown): boolean {
  return value === undefined || value === null || value === '';
}

// ---------------------------------------------------------------------------
// Gate pips.
// ---------------------------------------------------------------------------

function pipFor(state: string, terminal: readonly string[]): string {
  if (terminal.includes(state)) return PIP_TERMINAL;
  return state === 'blocked' ? PIP_BLOCKED : PIP_HOLDS;
}

/**
 * The terminal set a cell's pip must read, or null when the cell has no gate
 * meaning at all. Three cases, in order:
 *
 *  1. a declared `state` field   → the schema's own gate-terminal set (T008 ruling b);
 *  2. a declared enum that names `gate_terminal` → that enum's set (workshop-002
 *     Ruling 2: enums are general-purpose, and a schema says which values pass);
 *  3. an UNDECLARED field literally named `state` → the schema's set, because that
 *     is the same structural convention `deriveState` itself uses, and A3 says an
 *     unvalidated interior still renders.
 *
 * An enum with no `gate_terminal` deliberately falls through to null — it is a
 * vocabulary, not a gate, and pipping it would invent a semantic the schema declined.
 */
function terminalSetFor(
  field: string,
  shape: DdShape | undefined,
  schema: ResolvedDdSchema,
  gateTerminal: readonly string[],
): readonly string[] | null {
  if (shape === undefined) return field === 'state' ? gateTerminal : null;
  if (shape.type === 'state') return gateTerminal;
  if (shape.type === 'enum' && shape.enum) {
    return schema.enums?.[shape.enum]?.gate_terminal ?? null;
  }
  return null;
}

/** `[~] 3/5` — the derived-state row summary. Suppressed when there is nothing to count. */
function summarise(derived: DdDerivedState): string | null {
  if (derived.total === 0) return null;
  const pip = derived.complete ? PIP_TERMINAL : derived.terminal > 0 ? PIP_PARTIAL : PIP_HOLDS;
  return `${pip} ${derived.terminal}/${derived.total}`;
}

// ---------------------------------------------------------------------------
// Links — heading-only anchors (workshop-001 § Anchors).
// ---------------------------------------------------------------------------

/** Resolve a same-document address to the section (or map entry) it names. */
export function sectionForAddress(doc: DdDoc, address: DdAddress): DdSection | null {
  const sectionName = address.segments[0]?.value;
  if (sectionName === undefined) return null;
  const section = doc.sections.find((entry) => entry.name === sectionName);
  if (!section) return null;
  const key = address.segments[1]?.value;
  if (key === undefined) return section;
  // Only a MAP section has addressable interiors that own a heading of their own;
  // an array member lands on its section heading, exactly as the workshop ruled.
  if (!isRecord(section.value) || !(key in section.value)) return null;
  return { name: key, value: section.value[key] };
}

/**
 * Render a link cell: the id stays visible in the link text, the target is the
 * NEAREST HEADING — never a synthetic HTML anchor. A same-document map entry owns
 * its own `###` heading, so it anchors there; everything else anchors on its
 * section heading. Cross-file targets point at the sibling `.dd.md`, because that
 * is the artifact a human clicking the link can actually read.
 */
function renderLink(raw: string, doc: DdDoc, resolved: DdRenderContext): string {
  const address = parseAddress(raw);
  if (isAddressFailure(address)) return escapeCell(raw);

  const segments = address.segments;
  const text = segments[segments.length - 1]?.value ?? raw;

  let anchor: string;
  let derived: DdDerivedState | undefined;
  if (address.file === null) {
    const target = sectionForAddress(doc, address);
    anchor = headingSlug(target ? target.name : (segments[0]?.value ?? ''));
    if (target) {
      derived = deriveState(target, resolved.gateTerminal ?? DEFAULT_GATE_TERMINAL_STATES);
    }
  } else {
    // A cross-file interior is unknowable from here, so it anchors on the section
    // heading the address names — which the target's own render is guaranteed to emit.
    anchor = headingSlug(segments[0]?.value ?? '');
    derived = resolved.derived?.get(raw);
  }

  const file = address.file === null ? '' : address.file.replace(/\.dd\.json$/, '.dd.md');
  const link = `[${escapeCell(text)}](${file}#${anchor})`;
  const summary = derived ? summarise(derived) : null;
  return summary ? `${summary} ${link}` : link;
}

// ---------------------------------------------------------------------------
// Values.
// ---------------------------------------------------------------------------

interface CellDeps {
  doc: DdDoc;
  resolved: DdRenderContext;
}

function renderCustomType(
  value: unknown,
  type: string,
  field: string,
  shape: DdShape,
  location: string,
  deps: CellDeps,
): string {
  const ctx: DdAdapterContext = {
    type,
    field,
    shape,
    path: deps.resolved.path,
    location,
  };
  const rendered = deps.resolved.adapters?.render(value, ctx) ?? null;
  if (rendered !== null) return rendered;
  // W1 rule 4: raw value + type tag. Never blank, never a crash — and never
  // silent either: the adapter set has already recorded why on `issues`.
  const raw = typeof value === 'string' ? value : JSON.stringify(value);
  return `\`${escapeCell(raw ?? String(value))}\` ⟨type:${escapeCell(type)}⟩`;
}

function renderContainer(value: unknown, depth: number, deps: CellDeps, shape?: DdShape): string {
  if (Array.isArray(value)) {
    if (depth > MAX_CELL_DEPTH) return '⟨…⟩';
    const items = value.map((entry) => renderContainer(entry, depth + 1, deps, shape?.items));
    return depth <= 1 ? items.join(', ') : `[${items.join(', ')}]`;
  }
  if (isRecord(value)) {
    if (depth > MAX_CELL_DEPTH) return '⟨…⟩';
    const pairs = Object.entries(value).map(
      ([key, entry]) =>
        `${key}: ${renderContainer(entry, depth + 1, deps, shape?.fields?.[key] ?? shape?.valuesShape)}`,
    );
    return depth <= 1 ? pairs.join('; ') : `(${pairs.join('; ')})`;
  }
  // An address inside a container is as navigable as one in a cell of its own —
  // by its DECLARED `link` shape, or by the same undeclared-address inference
  // `renderCell` applies (A3 / workshop-002 Ruling 3). Without this, a schema
  // that says `array of link` silently renders plain text.
  if (
    typeof value === 'string' &&
    (shape?.type === 'link' || (!shape && looksLikeAddress(value)))
  ) {
    return renderLink(value, deps.doc, deps.resolved);
  }
  return renderScalar(value);
}

function renderScalar(value: unknown): string {
  if (isBlank(value)) return EMPTY_CELL;
  if (typeof value === 'boolean') return String(value);
  if (typeof value === 'number') return String(value);
  return escapeCell(String(value));
}

/**
 * Whether an UNDECLARED string should be read as an address. The grammar alone is
 * not enough — `"See #tasks"` parses — so the file half must also be either absent
 * (the bare-`#` same-document form) or an actual dd document. That keeps the
 * inference tight enough to be safe while still serving A3: an evidence entry's
 * `proven_by`/`pressure` links live in an interior the schema never declares
 * (workshop-002 Ruling 3), and rendering those as plain text would strand exactly
 * the links the design exists to make navigable.
 */
function looksLikeAddress(raw: string): boolean {
  const address = parseAddress(raw);
  if (isAddressFailure(address)) return false;
  return address.file === null || address.file.endsWith('.dd.json');
}

/** One table cell: shape-directed, falling back to structure when nothing is declared. */
function renderCell(
  value: unknown,
  field: string,
  shape: DdShape | undefined,
  location: string,
  deps: CellDeps,
): string {
  if (isBlank(value)) return EMPTY_CELL;

  if (shape && !BUILTIN_TYPES.has(shape.type)) {
    return renderCustomType(value, shape.type, field, shape, location, deps);
  }

  const gateTerminal = deps.resolved.gateTerminal ?? DEFAULT_GATE_TERMINAL_STATES;
  const terminal = terminalSetFor(field, shape, deps.resolved.schema, gateTerminal);
  if (terminal && typeof value === 'string') {
    return `${pipFor(value, terminal)} ${escapeCell(value)}`;
  }

  if (
    typeof value === 'string' &&
    (shape?.type === 'link' || (!shape && looksLikeAddress(value)))
  ) {
    return renderLink(value, deps.doc, deps.resolved);
  }

  if (Array.isArray(value) || isRecord(value)) return renderContainer(value, 1, deps, shape);
  return renderScalar(value);
}

// ---------------------------------------------------------------------------
// Tables.
// ---------------------------------------------------------------------------

function renderTable(columns: readonly string[], rows: readonly string[][]): string {
  const header = `| ${columns.join(' | ')} |`;
  const divider = `| ${columns.map(() => '---').join(' | ')} |`;
  return [header, divider, ...rows.map((row) => `| ${row.join(' | ')} |`)].join('\n');
}

/**
 * Declared columns first, in declaration order, then whatever the data actually
 * carries, in first-seen order. A3: an interior the schema never declared still
 * renders — an unvalidated field is invisible to the validator, not to the reader.
 */
function columnsFor(
  rows: readonly Record<string, unknown>[],
  shape: DdShape | undefined,
): string[] {
  const declared = Object.keys(shape?.fields ?? {});
  const columns = [...declared];
  for (const row of rows) {
    for (const key of Object.keys(row)) {
      if (!columns.includes(key)) columns.push(key);
    }
  }
  return columns;
}

function renderObjectRows(
  rows: readonly Record<string, unknown>[],
  itemShape: DdShape | undefined,
  location: string,
  deps: CellDeps,
): string {
  const columns = columnsFor(rows, itemShape);
  const body = rows.map((row, index) =>
    columns.map((column) =>
      renderCell(
        row[column],
        column,
        itemShape?.fields?.[column],
        `${location}[${index}].${column}`,
        deps,
      ),
    ),
  );
  return renderTable(columns, body);
}

/** An object section rendered as its own two-column table — the shape's declared fields first. */
function renderFieldTable(
  value: Record<string, unknown>,
  shape: DdShape | undefined,
  location: string,
  deps: CellDeps,
): string {
  const fields = columnsFor([value], shape);
  if (fields.length === 0) return '_No fields._';
  const rows = fields.map((field) => [
    escapeCell(field),
    renderCell(value[field], field, shape?.fields?.[field], `${location}.${field}`, deps),
  ]);
  return renderTable(['Field', 'Value'], rows);
}

// ---------------------------------------------------------------------------
// Sections.
// ---------------------------------------------------------------------------

/**
 * A keyed collection (the evidence section: one list per task id) versus a plain
 * field object. The discriminator is the schema plus the data, never a hard-coded
 * section name: a shape that declares no fields AND whose every value is itself a
 * container is a map, and each key earns its own heading so instance links have a
 * nearest heading to land on.
 */
function isKeyedMap(value: Record<string, unknown>, shape: DdShape | undefined): boolean {
  const entries = Object.values(value);
  if (Object.keys(shape?.fields ?? {}).length > 0) return false;
  return entries.length > 0 && entries.every((entry) => Array.isArray(entry) || isRecord(entry));
}

function renderSectionBody(section: DdSection, deps: CellDeps): string {
  const declared = deps.resolved.schema.sections[section.name]?.shape;
  const location = `$.sections[${section.name}]`;
  const value = section.value;

  if (Array.isArray(value)) {
    if (value.length === 0) return '_No entries._';
    if (value.every((entry) => isRecord(entry))) {
      return renderObjectRows(value as Record<string, unknown>[], declared?.items, location, deps);
    }
    return value
      .map((entry) => `- ${typeof entry === 'string' ? entry : renderContainer(entry, 1, deps)}`)
      .join('\n');
  }

  if (isRecord(value)) {
    if (!isKeyedMap(value, declared)) return renderFieldTable(value, declared, location, deps);
    return Object.entries(value)
      .map(([key, entry]) => {
        const body = renderSectionBody(
          { name: key, value: entry },
          // A map entry is addressed through its own key, so its interiors are
          // shaped by the map's `items`/`fields` if declared, and by the data if not.
          deps,
        );
        return `### ${key}\n\n${body}`;
      })
      .join('\n\n');
  }

  if (isBlank(value)) return '_Empty._';
  // Block context is verbatim: this is prose, not a cell, so nothing can break a row.
  return String(value);
}

/**
 * The document heading. The first object section carrying a non-empty string
 * `title` names the document — a convention, not a hard-coded section name, so it
 * holds for every exemplar schema. With no title anywhere, the source filename is
 * the honest answer.
 */
function documentTitle(doc: DdDoc, path: string): string {
  for (const section of doc.sections) {
    if (isRecord(section.value) && typeof section.value.title === 'string') {
      const title = section.value.title.trim();
      if (title.length > 0) return title;
    }
  }
  return basename(path);
}

// ---------------------------------------------------------------------------
// The renderer.
// ---------------------------------------------------------------------------

/**
 * Render one deterministic document to its canonical markdown. PURE — `(doc,
 * resolved) => string`: no fs, no `node:*`, no clock, no `process`, no envelopes.
 * Every cross-document fact arrives precomputed on `resolved` (F-12), so the same
 * inputs always produce the same bytes, which is exactly what makes
 * `dd build --check` a usable drift gate.
 *
 * Only the BASENAME of `resolved.path` is rendered: a golden file that pinned an
 * absolute path would be machine-specific, and the sibling `.dd.md` always sits
 * beside its `.dd.json` anyway.
 */
export function renderDd(doc: DdDoc, resolved: DdRenderContext): string {
  const deps: CellDeps = { doc, resolved };
  const blocks: string[] = [
    `${RENDER_BANNER}\n# ${documentTitle(doc, resolved.path)}`,
    [
      `**Schema**: ${doc.dd.schema}`,
      `**Source**: ${basename(resolved.path)}`,
      `**Sections**: ${doc.sections.length}`,
    ].join(' · '),
  ];

  for (const section of doc.sections) {
    blocks.push(`## ${section.name}\n\n${renderSectionBody(section, deps)}`);
  }

  if (doc.references.length > 0) {
    const rows = doc.references.map((reference) => [
      escapeCell(reference.path),
      escapeCell(reference.sha),
      reference.mode,
    ]);
    blocks.push(`## references\n\n${renderTable(['path', 'sha', 'mode'], rows)}`);
  }

  return `${blocks.join('\n\n')}\n`;
}
