import type { HarnessVerb } from '@ai-substrate/engineering-harness/contract';

/**
 * `harness checks` — the mandated quality gate for THIS repo (the harness's home).
 *
 * The single command an agent runs before considering work "done", and the SAME
 * command CI runs (the CI `build-test` job calls `harness checks`, so local and CI
 * can't drift). It COMPOSES the repo's existing deterministic checks (rather than
 * re-implementing them) into one honest envelope, so the gate has one definition that
 * grows as the team adds checks:
 *
 *   - tests        — `npx vitest run --coverage` in harness/cli  (hard gate; coverage feeds CI's lcov upload)
 *   - biome        — `npx biome check harness/cli`               (hard gate: lint/format)
 *   - typecheck    — `npx tsc --noEmit -p …/tsconfig.json`       (hard gate)
 *   - check:docs   — `npm run check:docs`                        (hard gate: generated-docs drift)
 *   - check:flows  — `npm run check:flows`                       (hard gate: flow schema/render drift)
 *   - check:telemetry-fixtures — `npm run check:telemetry-fixtures` (hard gate: telemetry golden drift)
 *   - check:doctrine-parity — `npm run check:doctrine-parity`    (warn-launch: degraded; harness chore/seam doctrine drift; SKIPS=ok when the-flow absent — CI; fails-by-default on deploy-lag, so non-blocking)
 *   - arch-check   — `harness arch-check`                        (warn-launch: degraded)
 *   - skills-check — `harness skills-check`                      (hard gate: error on violation)
 *   - markdown-lint— `harness markdown-lint`                     (warn-launch: degraded)
 *   - windows-check— `harness windows-check`                     (warn-launch: degraded)
 *
 * Aggregation (honest, never fakes green): any sub-gate `error` => checks error/exit 1;
 * else any `degraded`/`unconfigured` => checks degraded/exit 0 (the repo's warn-launch
 * posture — visible, non-blocking); all clean => ok/exit 0.
 *
 * PREREQUISITE: the caller must have built the core (`npm run build`) so `bin/harness.js`
 * (which runs from `dist/`) and the drift guards resolve — CI builds first. The gate
 * verbs themselves load fresh from `.harness/extensions/` src.
 *
 * Guardrails (cf. arch-check): no `node:*` imports; all I/O via `ctx.exec`/`ctx.fs`;
 * never throws; every non-ok result carries a `next_action`. It does not auto-fix
 * (unlike `just fft`, which mutates) — though the `check:docs`/`check:flows` drift
 * guards regenerate-then-diff, so a drift leaves the regenerated bytes in the tree.
 */

const CLI_DIR = 'harness/cli';

type GateStatus = 'ok' | 'degraded' | 'error' | 'unconfigured';
interface GateResult {
  name: string;
  status: GateStatus;
  exit: number;
  note: string;
}

/**
 * Run one shell-command gate. `severity` picks how a non-zero exit is reported:
 *  - `'hard'` (default) → `error` (blocks: any non-zero exit => `checks` exit 1).
 *  - `'warn'` → `degraded` (warn-launch: visible finding, non-blocking/exit 0) — the same
 *    posture as `arch-check`/`markdown-lint`. Used for gates whose red is environment-fragile
 *    (e.g. `check:doctrine-parity`, which keys on the *deployed* the-flow and so fails by
 *    default on deploy-lag), where a real drift should surface as a finding, not a build break.
 */
async function runCmdGate(
  ctx: Parameters<HarnessVerb['run']>[0],
  name: string,
  cmd: string,
  args: string[],
  opts: { cwd: string; failNote: string; severity?: 'hard' | 'warn' },
): Promise<GateResult> {
  const r = await ctx.exec(cmd, args, { cwd: opts.cwd });
  if (r.ok) return { name, status: 'ok', exit: r.code, note: '' };
  // Surface a short tail of the real output so a CI failure says WHY, not just the hint
  // (the composite captures sub-stdout, so this note is the only breadcrumb in the log).
  const tail = (r.stderr || r.stdout || '').trimEnd().split('\n').slice(-3).join(' ');
  const status: GateStatus = opts.severity === 'warn' ? 'degraded' : 'error';
  return { name, status, exit: r.code, note: tail ? `${opts.failNote} — ${tail}` : opts.failNote };
}

/** Pull the failure-relevant lines out of a vitest run (skip the coverage table / noise),
 * so a CI failure carries WHY in its envelope note (the composite captures sub-stdout). */
function vitestFailSummary(stdout: string, stderr: string): string {
  const lines = `${stdout}\n${stderr}`.split('\n');
  const hits = lines.filter((l) =>
    /\bFAIL\b|❯|AssertionError|\bError:|Expected|Received|Unhandled|\bTests\b.*\bfailed\b|\bTest Files\b.*\bfailed\b/.test(
      l,
    ),
  );
  return (hits.length > 0 ? hits.slice(0, 30) : lines.slice(-20)).join('\n').slice(0, 4000);
}

/** Run one harness sub-verb via the repo bin and read its envelope status. */
async function runVerbGate(
  ctx: Parameters<HarnessVerb['run']>[0],
  verb: string,
): Promise<GateResult> {
  // `verb` may name a sub-verb (`dd doctor`), so it is split into argv rather
  // than passed as one argument — commander would never match the pair otherwise.
  const r = await ctx.exec('node', [`${CLI_DIR}/bin/harness.js`, ...verb.split(' '), '--json'], {
    cwd: ctx.cwd,
  });
  try {
    const j = JSON.parse(r.stdout) as { status?: GateStatus; next_action?: string };
    const status = (j.status ?? (r.ok ? 'ok' : 'error')) as GateStatus;
    return { name: verb, status, exit: r.code, note: status === 'ok' ? '' : (j.next_action ?? '') };
  } catch {
    // No parseable envelope — fall back to the exit code (honest, never green-by-default).
    return {
      name: verb,
      status: r.ok ? 'ok' : 'error',
      exit: r.code,
      note: r.ok ? '' : r.stderr.trimEnd().split('\n').slice(-4).join(' '),
    };
  }
}

const checks: HarnessVerb = {
  name: 'checks',
  summary:
    'The mandated quality gate (the SAME command CI runs): composes vitest+coverage, biome, typecheck, the docs/flows/telemetry drift guards, and arch/skills/markdown/windows-check into one honest envelope. Run it before work is "done".',
  description:
    'Runs the repo\u2019s deterministic checks and aggregates: tests (`vitest run --coverage`), biome, typecheck, ' +
    'check:docs, check:flows, check:telemetry-fixtures, and skills-check are hard gates (error => exit 1); ' +
    'check:doctrine-parity, root-invocation-smoke, arch-check, markdown-lint, windows-check are warn-launch ' +
    '(findings => degraded/exit 0). Any hard-gate error => ' +
    'checks error/exit 1; otherwise any degraded/unconfigured gate => checks degraded/exit 0; all clean => ok/exit 0. ' +
    'PREREQUISITE: `npm run build` first (the bin + drift guards need `dist/`). `harness boot` composes this; CI ' +
    'calls it. Extend the gate by adding a line here as the team grows. See `harness instructions checks`.',
  async run(ctx) {
    try {
      if (!ctx.fs.exists(`${ctx.cwd}/${CLI_DIR}/vitest.config.ts`)) {
        return ctx.unconfigured(
          `No ${CLI_DIR}/vitest.config.ts at ${ctx.cwd} \u2014 run \`harness checks\` from the repo root.`,
        );
      }

      const gates: GateResult[] = [];
      const root = ctx.cwd;

      // Hard gate 1 \u2014 the unit-test suite (behaviour proof). `--coverage` so the one
      // test run also emits the lcov CI uploads (no second test pass needed).
      const started = Date.now();
      const test = await ctx.exec('npx', ['vitest', 'run', '--coverage'], { cwd: `${root}/${CLI_DIR}` });
      gates.push({
        name: 'tests',
        status: test.ok ? 'ok' : 'error',
        exit: test.code,
        note: test.ok
          ? ''
          : `The vitest suite failed \u2014 reproduce with \`just test\`.\n${vitestFailSummary(test.stdout, test.stderr)}`,
      });

      // Hard gates \u2014 lint / typecheck / drift guards (read src; mirror CI's static gates).
      gates.push(
        await runCmdGate(ctx, 'biome', 'npx', ['biome', 'check', CLI_DIR], {
          cwd: root,
          failNote: 'Biome found lint/format issues \u2014 run `just fix` then re-run.',
        }),
      );
      gates.push(
        await runCmdGate(ctx, 'typecheck', 'npx', ['tsc', '--noEmit', '-p', `${CLI_DIR}/tsconfig.json`], {
          cwd: root,
          failNote: 'Typecheck failed \u2014 fix the type errors reported above.',
        }),
      );
      gates.push(
        await runCmdGate(ctx, 'check:docs', 'npm', ['run', 'check:docs'], {
          cwd: root,
          failNote: 'Generated docs bundle drifted \u2014 run `npm run gen:docs` and commit the result.',
        }),
      );
      gates.push(
        await runCmdGate(ctx, 'check:flows', 'npm', ['run', 'check:flows'], {
          cwd: root,
          failNote: 'Flow schemas/renders drifted \u2014 run `npm run gen:flows` and commit the result.',
        }),
      );
      gates.push(
        await runCmdGate(ctx, 'check:telemetry-fixtures', 'npm', ['run', 'check:telemetry-fixtures'], {
          cwd: root,
          failNote:
            'Telemetry goldens drifted \u2014 they are frozen compatibility evidence; preserve them and run `npm run check:telemetry-fixtures`.',
        }),
      );
      // Doctrine-parity guard (WARN-LAUNCH): the harness chore/seam `doctrine-parity:039` block
      // must be byte-identical in `skills/eng-harness-flow/SKILL.md` and the-flow's canonical
      // `harness-seams.md`. SKIPS (exit 0) when the-flow is absent (CI / a the-flow-less machine)
      // \u2014 eng-harness-flow never depends on the-flow at runtime. A located-but-divergent copy is
      // a `degraded` finding (NOT a build break): it keys on the *deployed* the-flow, so it fails
      // by default on deploy-lag (in-repo block edited, the-flow not yet re-deployed) \u2014 too
      // environment-fragile for a hard gate. Real drift stays visible; re-deploy the-flow to clear.
      gates.push(
        await runCmdGate(ctx, 'check:doctrine-parity', 'npm', ['run', 'check:doctrine-parity'], {
          cwd: root,
          severity: 'warn',
          failNote:
            'Harness chore/seam doctrine drifted \u2014 edit BOTH the `doctrine-parity:039` blocks (the-flow `harness-seams.md` + `eng-harness-flow/SKILL.md`) byte-identical, then re-deploy the-flow.',
        }),
      );

      // Root-invocation smoke (P2 DL-008, decided here): the repo sanctions a
      // repo-root `vitest run` via the root vitest.config.ts, and until now
      // NOTHING exercised it \u2014 two sanctioned invocations, one of them unproven,
      // which is exactly how a cwd bug hid for a phase. A SMOKE rather than the
      // full suite: the gate already runs every test once from harness/cli, so the
      // open question is whether the root invocation resolves at all, and one
      // CLI-spawning file answers that for seconds rather than a second full pass.
      //
      // Re-aimed from `test/acts/dd.test.ts` to `test/acts/plan-fence.test.ts`
      // (plan 080 tk-000d): the dd verb suite was deleted with the fork. The
      // requirement on this file is only that it SPAWNS THE CLI and is small \u2014
      // plan-fence does both. If it is ever deleted, re-aim rather than drop the
      // gate: the thing under test is the root invocation, not the file.
      gates.push(
        await runCmdGate(
          ctx,
          'root-invocation-smoke',
          'npx',
          ['vitest', 'run', 'test/acts/plan-fence.test.ts'],
          {
            cwd: root,
            severity: 'warn',
            failNote:
              'The repo-root vitest invocation failed \u2014 either fix it or delete the root vitest.config.ts; the repo must not sanction an invocation nothing runs.',
          },
        ),
      );

      // Composed harness sub-verbs.
      gates.push(await runVerbGate(ctx, 'arch-check'));
      gates.push(await runVerbGate(ctx, 'skills-check'));
      gates.push(await runVerbGate(ctx, 'markdown-lint'));
      gates.push(await runVerbGate(ctx, 'windows-check'));

      const durationMs = Date.now() - started;
      const summary = gates.map((g) => `${g.name}:${g.status}`).join(' ');
      const failed = gates.filter((g) => g.status === 'error');
      const soft = gates.filter((g) => g.status === 'degraded' || g.status === 'unconfigured');
      const data = { durationMs, summary, gates };

      if (failed.length > 0) {
        return ctx.error(
          'E_CHECKS_FAILED',
          `Quality gate failed: ${failed.map((g) => g.name).join(', ')} did not pass.`,
          {
            details: data,
            next_action: `Fix: ${failed
              .map((g) => `[${g.name}] ${g.note}`)
              .join(' \u2014 ')} Then re-run \`harness checks\`.`,
          },
        );
      }
      if (soft.length > 0) {
        return ctx.degraded(
          data,
          `Warn-launch findings (non-blocking): ${soft
            .map((g) => `[${g.name}] ${g.note}`)
            .join(' \u2014 ')} Run each verb directly for detail; promote to a hard gate once clean.`,
        );
      }
      return ctx.ok(data, { next_action: 'All gates green \u2014 work is safe to call done.' });
    } catch (e) {
      return ctx.error('E_CHECKS_UNEXPECTED', 'checks failed unexpectedly', {
        details: e instanceof Error ? e.message : String(e),
        next_action: 'Run the gates directly (`just test`, `harness arch-check`, \u2026) to localise, then re-run `harness checks`.',
      });
    }
  },
};

export default checks;
