import type { HarnessVerb } from '@ai-substrate/engineering-harness/contract';

/**
 * `harness checks` — the mandated quality gate for THIS repo (the harness's home).
 *
 * The single command an agent runs before considering work "done", and the SAME
 * command CI runs (the CI `build-test` job calls `harness checks`, so local and CI
 * can't drift). It COMPOSES the repo's existing deterministic checks (rather than
 * re-implementing them) into one honest envelope, so the gate has one definition that
 * grows as the team adds checks:
 *
 *   - tests        — `npx vitest run --coverage` in harness/cli  (hard gate; coverage feeds CI's lcov upload)
 *   - biome        — `npx biome check harness/cli`               (hard gate: lint/format)
 *   - typecheck    — `npx tsc --noEmit -p …/tsconfig.json`       (hard gate)
 *   - check:docs   — `npm run check:docs`                        (hard gate: generated-docs drift)
 *   - check:flows  — `npm run check:flows`                       (hard gate: flow schema/render drift)
 *   - check:telemetry-fixtures — `npm run check:telemetry-fixtures` (hard gate: telemetry golden drift)
 *   - check:doctrine-parity — `npm run check:doctrine-parity`    (warn-launch: degraded; harness chore/seam doctrine drift; SKIPS=ok when the-flow absent — CI; fails-by-default on deploy-lag, so non-blocking)
 *   - arch-check   — `harness arch-check`                        (warn-launch: degraded)
 *   - skills-check — `harness skills-check`                      (hard gate: error on violation)
 *   - markdown-lint— `harness markdown-lint`                     (warn-launch: degraded)
 *   - windows-check— `harness windows-check`                     (warn-launch: degraded)
 *
 * Aggregation (honest, never fakes green): any sub-gate `error` => checks error/exit 1;
 * else any `degraded`/`unconfigured` => checks degraded/exit 0 (the repo's warn-launch
 * posture — visible, non-blocking); all clean => ok/exit 0.
 *
 * PREREQUISITE: the caller must have built the core (`npm run build`) so `bin/harness.js`
 * (which runs from `dist/`) and the drift guards resolve — CI builds first. The gate
 * verbs themselves load fresh from `.harness/extensions/` src.
 *
 * Guardrails (cf. arch-check): no `node:*` imports; all I/O via `ctx.exec`/`ctx.fs`;
 * never throws; every non-ok result carries a `next_action`. It does not auto-fix
 * (unlike `just fft`, which mutates) — though the `check:docs`/`check:flows` drift
 * guards regenerate-then-diff, so a drift leaves the regenerated bytes in the tree.
 */

const CLI_DIR = 'harness/cli';

type GateStatus = 'ok' | 'degraded' | 'error' | 'unconfigured';
interface GateResult {
  name: string;
  status: GateStatus;
  exit: number;
  note: string;
}

/**
 * Run one shell-command gate. `severity` picks how a non-zero exit is reported:
 *  - `'hard'` (default) → `error` (blocks: any non-zero exit => `checks` exit 1).
 *  - `'warn'` → `degraded` (warn-launch: visible finding, non-blocking/exit 0) — the same
 *    posture as `arch-check`/`markdown-lint`. Used for gates whose red is environment-fragile
 *    (e.g. `check:doctrine-parity`, which keys on the *deployed* the-flow and so fails by
 *    default on deploy-lag), where a real drift should surface as a finding, not a build break.
 */
async function runCmdGate(
  ctx: Parameters<HarnessVerb['run']>[0],
  name: string,
  cmd: string,
  args: string[],
  opts: { cwd: string; failNote: string; severity?: 'hard' | 'warn' },
): Promise<GateResult> {
  const r = await ctx.exec(cmd, args, { cwd: opts.cwd });
  if (r.ok) return { name, status: 'ok', exit: r.code, note: '' };
  // Surface a short tail of the real output so a CI failure says WHY, not just the hint
  // (the composite captures sub-stdout, so this note is the only breadcrumb in the log).
  const tail = (r.stderr || r.stdout || '').trimEnd().split('\n').slice(-3).join(' ');
  const status: GateStatus = opts.severity === 'warn' ? 'degraded' : 'error';
  return { name, status, exit: r.code, note: tail ? `${opts.failNote} — ${tail}` : opts.failNote };
}

/** Pull the failure-relevant lines out of a vitest run (skip the coverage table / noise),
 * so a CI failure carries WHY in its envelope note (the composite captures sub-stdout). */
function vitestFailSummary(stdout: string, stderr: string): string {
  const lines = `${stdout}\n${stderr}`.split('\n');
  const hits = lines.filter((l) =>
    /\bFAIL\b|❯|AssertionError|\bError:|Expected|Received|Unhandled|\bTests\b.*\bfailed\b|\bTest Files\b.*\bfailed\b/.test(
      l,
    ),
  );
  return (hits.length > 0 ? hits.slice(0, 30) : lines.slice(-20)).join('\n').slice(0, 4000);
}

/** Run one harness sub-verb via the repo bin and read its envelope status. */
async function runVerbGate(
  ctx: Parameters<HarnessVerb['run']>[0],
  verb: string,
): Promise<GateResult> {
  // `verb` may name a sub-verb (`dd doctor`), so it is split into argv rather
  // than passed as one argument — commander would never match the pair otherwise.
  const r = await ctx.exec('node', [`${CLI_DIR}/bin/harness.js`, ...verb.split(' '), '--json'], {
    cwd: ctx.cwd,
  });
  try {
    const j = JSON.parse(r.stdout) as { status?: GateStatus; next_action?: string };
    const status = (j.status ?? (r.ok ? 'ok' : 'error')) as GateStatus;
    return { name: verb, status, exit: r.code, note: status === 'ok' ? '' : (j.next_action ?? '') };
  } catch {
    // No parseable envelope — fall back to the exit code (honest, never green-by-default).
    return {
      name: verb,
      status: r.ok ? 'ok' : 'error',
      exit: r.code,
      note: r.ok ? '' : r.stderr.trimEnd().split('\n').slice(-4).join(' '),
    };
  }
}

/**
 * Stale `--ref` worktrees left by an earlier interrupted run.
 *
 * MEASURED, not assumed: killing a run mid-install leaves the worktree
 * registered, and `git worktree prune` does NOT reclaim it — prune only drops
 * entries whose directory is missing, and a half-installed tree still has one.
 * (During that test the prune ALSO removed an unrelated dead entry belonging to
 * another seat, which made the worktree count return to its baseline and look
 * like success. The count agreed; the thing it was supposed to prove did not.)
 *
 * These are REPORTED, never removed: a concurrent seat may legitimately be
 * running its own `--ref` gate, and nothing in the name distinguishes a crashed
 * tree from a live one. Deleting a peer's in-flight worktree would be exactly
 * the shared-state mutation this verb exists to end.
 */
async function findStaleRefWorktrees(
  ctx: Parameters<HarnessVerb['run']>[0],
  selfDir: string,
): Promise<string[]> {
  const r = await ctx.exec('git', ['worktree', 'list', '--porcelain'], { cwd: ctx.cwd });
  if (!r.ok) return [];
  return r.stdout
    .split('\n')
    .filter((l) => l.startsWith('worktree '))
    .map((l) => l.slice('worktree '.length).trim())
    .filter((p) => p.includes('harness-checks-ref-') && p !== selfDir);
}

/**
 * Run the gate against a REF, in a throwaway worktree that owns everything it
 * touches (#145).
 *
 * WHAT IT MEASURES, STATED POSITIVELY RATHER THAN AS A CAVEAT. `--ref` answers
 * "IS THIS REF SOUND?" — not "does my tree work right now". They are different
 * questions and this only answers the first. The isolation that makes it safe is
 * the same property that bounds it: because it builds fresh from the ref, it
 * CANNOT see local breakage — a stale `dist/`, a half-applied rebase, an
 * uninstalled dependency. That class is real and common (it bit this verb's own
 * landing), and a plain `harness checks` is what reports it. Adopting `--ref` as
 * a habitual replacement for the ordinary gate would silently retire an entire
 * category of finding.
 *
 * WHY THIS EXISTS. Measuring a gate against another ref used to mean making the
 * working tree look like that ref — and the cheapest way to do that is
 * `git stash`. In this repo the stash stack is SHARED across every worktree, so
 * a stash/pop pair races every other seat, and the loser silently inherits
 * someone else's uncommitted work into a tree they are about to commit from.
 * Three seats reached for it in one day, each while MEASURING rather than
 * delivering. The missing thing was never the warning; it was this verb.
 *
 * WHAT IT GUARANTEES, and how. The isolation is STRUCTURAL, not instructed:
 * nothing here runs in the caller's tree, so there is no advice to follow and no
 * care to take.
 *
 *  - The tree is a fresh `git worktree --detach` at the resolved sha.
 *  - It installs its OWN dependencies. This is not caution, it is a measured
 *    requirement: vitest writes `node_modules/.vite/vitest/<hash>/results.json`
 *    on an ordinary run, so a shared or symlinked `node_modules` would leak
 *    writes back into the caller's checkout — an UNTRACKED write, into a
 *    gitignored dir, invisible to `git status`. No dependency-sharing scheme is
 *    used, however clever: every one either shares a writable path or requires
 *    proving a negative about what the toolchain writes, and one unpredicted
 *    write has already been found.
 *  - Cleanup is unconditional (`finally`). The failure mode this verb REPLACES
 *    fails by silent acquisition; this one fails by leaving a stale worktree.
 *    MEASURED, because "acceptable by design" and "observed" are different
 *    claims: kill a run mid-install and the entry survives, and
 *    `git worktree prune` does NOT reclaim it — prune only drops entries whose
 *    directory is GONE, and a half-installed tree still has one. Recovery is
 *    `git worktree remove --force <path>`. So stale trees are surfaced in the
 *    envelope below with that exact command, rather than left for someone to
 *    discover via a puzzling `git worktree list`.
 *
 * Stale trees are REPORTED, never auto-removed. Another seat may be running a
 * `--ref` gate concurrently, and reaping by name alone cannot tell a crashed
 * tree from a live one — silently deleting a peer's in-flight worktree would be
 * a fresh instance of the shared-state mutation this verb exists to end.
 *
 * There is deliberately NO platform-divergent fast path (e.g. an APFS
 * copy-on-write clone of `node_modules`). It would mean the isolated tree is
 * built differently on each platform — two implementations of this function's
 * central guarantee, with the constantly-exercised one on the platform where
 * nothing goes wrong. Least-tested exactly where it is least-correct.
 */
async function runAgainstRef(
  ctx: Parameters<HarnessVerb['run']>[0],
  ref: string,
  keep: boolean,
): Promise<ReturnType<HarnessVerb['run']>> {
  if (!ctx.fsWrite) {
    return ctx.unconfigured(
      'checks --ref needs the fs-write port to create a temp worktree, and it is not available here.',
    );
  }

  // Resolve BEFORE building anything: a bad ref should cost nothing, and the
  // answer must be pinned to a sha rather than a moving name — a result
  // attributed to `main` is not reproducible once main moves.
  const rev = await ctx.exec('git', ['rev-parse', '--verify', `${ref}^{commit}`], { cwd: ctx.cwd });
  if (!rev.ok) {
    return ctx.error('E_CHECKS_BAD_REF', `Not a commit: ${ref}`, {
      details: rev.stderr.trim(),
      next_action: `Check the ref exists (\`git rev-parse ${ref}\`), then re-run \`harness checks --ref ${ref}\`.`,
    });
  }
  const sha = rev.stdout.trim();

  const dir = ctx.fsWrite.mkdtemp('harness-checks-ref-');
  const stale = await findStaleRefWorktrees(ctx, dir);
  let added = false;
  try {
    const add = await ctx.exec('git', ['worktree', 'add', '--detach', dir, sha], { cwd: ctx.cwd });
    if (!add.ok) {
      return ctx.error('E_CHECKS_WORKTREE', `Could not create an isolated worktree for ${ref}.`, {
        details: add.stderr.trim(),
        next_action: 'Run `git worktree prune` (a previous run may have left a stale entry), then retry.',
      });
    }
    added = true;

    // The isolated tree installs and builds for itself — see the note above on
    // why nothing is shared. `npm ci` is the honest price of the guarantee.
    for (const [label, cmd, args] of [
      ['install', 'npm', ['ci']],
      ['build', 'npm', ['run', 'build']],
    ] as const) {
      const r = await ctx.exec(cmd, [...args], { cwd: dir, timeoutMs: 15 * 60_000 });
      if (!r.ok) {
        return ctx.error('E_CHECKS_REF_PREPARE', `Could not ${label} ${ref} in isolation.`, {
          details: (r.stderr || r.stdout).trimEnd().split('\n').slice(-5).join('\n'),
          next_action: `The ref itself may not build. Reproduce with: git worktree add --detach /tmp/x ${sha} && cd /tmp/x && npm ci && npm run build`,
        });
      }
    }

    // The inner call carries NO `--ref`, which is what terminates the recursion.
    // Scope defaults to `all` here even though the inner default is `fast`: a
    // ref-scoped run is a deliberate verdict about a commit, not an inner-loop
    // iteration, so it should mean the whole gate unless the caller has said
    // otherwise. Telemetry is off — a measurement should not emit events.
    const scope = ctx.env.get('HARNESS_TEST_SCOPE') ?? 'all';
    const run = await ctx.exec('node', [`${CLI_DIR}/bin/harness.js`, 'checks', '--json'], {
      cwd: dir,
      timeoutMs: 60 * 60_000,
      env: { HARNESS_TEST_SCOPE: scope, HARNESS_NO_TELEMETRY: '1' },
    });

    let inner: { status?: GateStatus; data?: { durationMs?: number; summary?: string; gates?: GateResult[] } };
    try {
      inner = JSON.parse(run.stdout);
    } catch {
      return ctx.error('E_CHECKS_REF_UNREADABLE', `The isolated gate for ${ref} produced no readable envelope.`, {
        details: (run.stderr || run.stdout).trimEnd().split('\n').slice(-10).join('\n'),
        next_action: `Re-run with --keep to inspect the isolated tree, then run \`harness checks\` inside it by hand.`,
      });
    }

    // Provenance travels WITH the verdict: a number that cannot name its basis
    // is the stale-number problem this verb also exists to close.
    const data = {
      ref,
      sha,
      scope,
      isolated: true,
      durationMs: inner.data?.durationMs,
      summary: inner.data?.summary ?? '',
      gates: inner.data?.gates ?? [],
      ...(stale.length > 0 ? { staleWorktrees: stale } : {}),
    };
    const status = inner.status ?? (run.ok ? 'ok' : 'error');
    // Stale trees are NAMED, never reaped. Nothing in the name distinguishes a
    // crashed tree from a live one, and a concurrent seat may be mid-gate — so
    // auto-removing by prefix would make this verb a fresh instance of the
    // shared-state mutation it exists to end. The recovery command is spelled
    // out because `git worktree prune` does NOT reclaim these (measured: prune
    // only drops entries whose directory is gone) and because prune is itself
    // repo-global, so it can take another seat's entry with it.
    const staleNote =
      stale.length > 0
        ? ` NOTE: ${stale.length} stale --ref worktree(s) from an interrupted run — \`git worktree prune\` will NOT reclaim these (the directory still exists); use \`git worktree remove --force <path>\`: ${stale.join(', ')}`
        : '';
    const basis = `Gate run against ${ref} (${sha.slice(0, 12)}), test scope "${scope}", in an isolated worktree — your tree was not touched.${staleNote}`;

    if (status === 'error') {
      return ctx.error('E_CHECKS_FAILED', `Quality gate failed at ${ref} (${sha.slice(0, 12)}).`, {
        details: data,
        next_action: `${basis} Fix at that ref, or re-run \`harness checks\` in your own tree to compare.`,
      });
    }
    if (status === 'degraded' || status === 'unconfigured') {
      return ctx.degraded(data, `${basis} ${inner.data?.summary ?? ''}`);
    }
    return ctx.ok(data, { next_action: `${basis} All gates green at that ref.` });
  } finally {
    // Unconditional: a stale worktree is the failure mode this design ACCEPTS in
    // exchange for killing the silent one, and it only stays benign if it is
    // actually cleaned up. `--keep` is the one exception and it is explicit.
    if (added && !keep) {
      await ctx.exec('git', ['worktree', 'remove', '--force', dir], { cwd: ctx.cwd });
    }
  }
}

const checks: HarnessVerb = {
  name: 'checks',
  summary:
    'The mandated quality gate (the SAME command CI runs): composes vitest+coverage, biome, typecheck, the docs/flows/telemetry drift guards, and arch/skills/markdown/windows-check into one honest envelope. Run it before work is "done".',
  description:
    'Runs the repo\u2019s deterministic checks and aggregates: tests (`vitest run --coverage`), biome, typecheck, ' +
    'check:docs, check:flows, check:telemetry-fixtures, and skills-check are hard gates (error => exit 1); ' +
    'check:doctrine-parity, root-invocation-smoke, arch-check, markdown-lint, windows-check are warn-launch ' +
    '(findings => degraded/exit 0). Any hard-gate error => ' +
    'checks error/exit 1; otherwise any degraded/unconfigured gate => checks degraded/exit 0; all clean => ok/exit 0. ' +
    'PREREQUISITE: `npm run build` first (the bin + drift guards need `dist/`). `harness boot` composes this; CI ' +
    'calls it. Extend the gate by adding a line here as the team grows. See `harness instructions checks`.',
  options: [
    {
      flags: '--ref <ref>',
      description:
        'answer "is REF sound?" — runs the gate against REF in a throwaway worktree that builds and installs for itself, so your working tree is never touched (use instead of stashing to measure). It measures the REF, not your tree: because it builds fresh from REF it cannot see local breakage such as a stale dist/, which a plain `harness checks` does report',
    },
    { flags: '--keep', description: 'keep the isolated worktree for inspection (implies --ref)' },
  ],
  async run(ctx) {
    try {
      if (!ctx.fs.exists(`${ctx.cwd}/${CLI_DIR}/vitest.config.ts`)) {
        return ctx.unconfigured(
          `No ${CLI_DIR}/vitest.config.ts at ${ctx.cwd} \u2014 run \`harness checks\` from the repo root.`,
        );
      }

      // FIRST, before any gate can touch this tree: a `--ref` run must not
      // execute a single check here. The gates write tracked files (`gen:docs`
      // and friends regenerate artifacts), so a `--ref` that merely changed what
      // was MEASURED while still running HERE would remove the stash and keep
      // the mutation — the same hazard wearing a safer name.
      const refOpt = ctx.options.ref;
      if (typeof refOpt === 'string' && refOpt !== '') {
        return await runAgainstRef(ctx, refOpt, ctx.options.keep === true);
      }

      const gates: GateResult[] = [];
      const root = ctx.cwd;

      // Hard gate 1 \u2014 the unit-test suite (behaviour proof). `--coverage` so the one
      // test run also emits the lcov CI uploads (no second test pass needed).
      //
      // SCOPE IS PART OF THE VERDICT. The suite defaults to the FAST scope (see
      // SLOW_TESTS in harness/cli/vitest.config.ts), so a local `checks` proves LESS
      // than CI's does. That reduction is declared here rather than left to the
      // subprocess's stderr banner, which no JSON consumer ever sees: a gate that
      // quietly narrows what it proves is worse than a slow one.
      //
      // THE COUNT IS READ FROM THE RUN, NEVER REMEMBERED. It used to be the literal
      // `12`, which silently became wrong the moment SLOW_TESTS changed size (#108
      // removed two entries and this string kept saying 12). A second copy of a
      // number with nothing keeping it true is a figure that reads as counted and
      // is not. If the banner cannot be parsed, say so with no number at all.
      const started = Date.now();
      const scope = ctx.env.get('HARNESS_TEST_SCOPE') ?? 'fast';
      const test = await ctx.exec('npx', ['vitest', 'run', '--coverage'], { cwd: `${root}/${CLI_DIR}` });
      const skipped = /(\d+) slow file\(s\) SKIPPED/.exec(test.stderr)?.[1];
      const scopeNote =
        scope === 'all'
          ? 'full suite'
          : `${scope} scope \u2014 ${skipped ? `${skipped} slow file(s)` : 'the slow files'} NOT run; set HARNESS_TEST_SCOPE=all for the full suite (CI does)`;
      gates.push({
        name: 'tests',
        status: test.ok ? 'ok' : 'error',
        exit: test.code,
        note: test.ok
          ? scopeNote
          : `The vitest suite failed (${scopeNote}) \u2014 reproduce with \`just test\`.\n${vitestFailSummary(test.stdout, test.stderr)}`,
      });

      // Hard gates \u2014 lint / typecheck / drift guards (read src; mirror CI's static gates).
      gates.push(
        await runCmdGate(ctx, 'biome', 'npx', ['biome', 'check', CLI_DIR], {
          cwd: root,
          failNote: 'Biome found lint/format issues \u2014 run `just fix` then re-run.',
        }),
      );
      gates.push(
        await runCmdGate(ctx, 'typecheck', 'npx', ['tsc', '--noEmit', '-p', `${CLI_DIR}/tsconfig.json`], {
          cwd: root,
          failNote: 'Typecheck failed \u2014 fix the type errors reported above.',
        }),
      );
      gates.push(
        await runCmdGate(ctx, 'check:docs', 'npm', ['run', 'check:docs'], {
          cwd: root,
          failNote: 'Generated docs bundle drifted \u2014 run `npm run gen:docs` and commit the result.',
        }),
      );
      gates.push(
        await runCmdGate(ctx, 'check:flows', 'npm', ['run', 'check:flows'], {
          cwd: root,
          failNote: 'Flow schemas/renders drifted \u2014 run `npm run gen:flows` and commit the result.',
        }),
      );
      gates.push(
        await runCmdGate(ctx, 'check:telemetry-fixtures', 'npm', ['run', 'check:telemetry-fixtures'], {
          cwd: root,
          failNote:
            'Telemetry goldens drifted \u2014 they are frozen compatibility evidence; preserve them and run `npm run check:telemetry-fixtures`.',
        }),
      );
      // Doctrine-parity guard (WARN-LAUNCH): the harness chore/seam `doctrine-parity:039` block
      // must be byte-identical in `skills/eng-harness-flow/SKILL.md` and the-flow's canonical
      // `harness-seams.md`. SKIPS (exit 0) when the-flow is absent (CI / a the-flow-less machine)
      // \u2014 eng-harness-flow never depends on the-flow at runtime. A located-but-divergent copy is
      // a `degraded` finding (NOT a build break): it keys on the *deployed* the-flow, so it fails
      // by default on deploy-lag (in-repo block edited, the-flow not yet re-deployed) \u2014 too
      // environment-fragile for a hard gate. Real drift stays visible; re-deploy the-flow to clear.
      gates.push(
        await runCmdGate(ctx, 'check:doctrine-parity', 'npm', ['run', 'check:doctrine-parity'], {
          cwd: root,
          severity: 'warn',
          failNote:
            'Harness chore/seam doctrine drifted \u2014 edit BOTH the `doctrine-parity:039` blocks (the-flow `harness-seams.md` + `eng-harness-flow/SKILL.md`) byte-identical, then re-deploy the-flow.',
        }),
      );

      // Root-invocation smoke (P2 DL-008, decided here): the repo sanctions a
      // repo-root `vitest run` via the root vitest.config.ts, and until now
      // NOTHING exercised it \u2014 two sanctioned invocations, one of them unproven,
      // which is exactly how a cwd bug hid for a phase. A SMOKE rather than the
      // full suite: the gate already runs every test once from harness/cli, so the
      // open question is whether the root invocation resolves at all, and one
      // CLI-spawning file answers that for seconds rather than a second full pass.
      //
      // Re-aimed from `test/acts/dd.test.ts` to `test/acts/plan-fence.test.ts`
      // (plan 080 tk-000d): the dd verb suite was deleted with the fork. The
      // requirement on this file is only that it SPAWNS THE CLI and is small \u2014
      // plan-fence does both. If it is ever deleted, re-aim rather than drop the
      // gate: the thing under test is the root invocation, not the file.
      gates.push(
        await runCmdGate(
          ctx,
          'root-invocation-smoke',
          'npx',
          ['vitest', 'run', 'test/acts/plan-fence.test.ts'],
          {
            cwd: root,
            severity: 'warn',
            failNote:
              'The repo-root vitest invocation failed \u2014 either fix it or delete the root vitest.config.ts; the repo must not sanction an invocation nothing runs.',
          },
        ),
      );

      // Composed harness sub-verbs.
      gates.push(await runVerbGate(ctx, 'arch-check'));
      gates.push(await runVerbGate(ctx, 'skills-check'));
      gates.push(await runVerbGate(ctx, 'markdown-lint'));
      gates.push(await runVerbGate(ctx, 'windows-check'));

      const durationMs = Date.now() - started;
      const summary = gates.map((g) => `${g.name}:${g.status}`).join(' ');
      const failed = gates.filter((g) => g.status === 'error');
      const soft = gates.filter((g) => g.status === 'degraded' || g.status === 'unconfigured');
      const data = { durationMs, summary, gates };

      if (failed.length > 0) {
        return ctx.error(
          'E_CHECKS_FAILED',
          `Quality gate failed: ${failed.map((g) => g.name).join(', ')} did not pass.`,
          {
            details: data,
            next_action: `Fix: ${failed
              .map((g) => `[${g.name}] ${g.note}`)
              .join(' \u2014 ')} Then re-run \`harness checks\`.`,
          },
        );
      }
      if (soft.length > 0) {
        return ctx.degraded(
          data,
          `Warn-launch findings (non-blocking): ${soft
            .map((g) => `[${g.name}] ${g.note}`)
            .join(' \u2014 ')} Run each verb directly for detail; promote to a hard gate once clean.`,
        );
      }
      return ctx.ok(data, { next_action: 'All gates green \u2014 work is safe to call done.' });
    } catch (e) {
      return ctx.error('E_CHECKS_UNEXPECTED', 'checks failed unexpectedly', {
        details: e instanceof Error ? e.message : String(e),
        next_action: 'Run the gates directly (`just test`, `harness arch-check`, \u2026) to localise, then re-run `harness checks`.',
      });
    }
  },
};

export default checks;
