#!/usr/bin/env node
/**
 * Build-time flow-schema bundler (plan 024, Phase 1 task T003; AC-11).
 *
 * Reads the harness-OWNED flow schemas + templates
 * (`harness/cli/src/services/flow/schemas/*.schema.json` and `*.template.json`)
 * and emits a committed TypeScript module (`schemas-content.ts`) exporting
 * `BUNDLED_FLOW_SCHEMAS` + `BUNDLED_FLOW_TEMPLATES` maps (keyed by file stem).
 * `tsc` compiles that into `dist` like any other source file, so the bundled
 * built-ins ship with the CLI with ZERO runtime fs/path — the loader resolves
 * `--schema` › `.harness/schemas/flows/<type>.schema.json` › THIS bundle › E304.
 *
 * Mirrors `scripts/gen-docs.mjs`: pure Node, zero deps; content embedded via
 * `JSON.stringify` (robust escaping); output biome-normalised so the committed
 * file is byte-stable across regenerations — which is what makes the Phase-2 CI
 * drift guard (`check:flows`) reliable.
 *
 * Harness-owned schemas bundle from the schemas dir. Additionally, an explicit
 * allowlist of SKILL-owned types bundles from `skills/builder/references/` —
 * today exactly `flight-plan` (plan 081, Jordan 2026-08-09: "pij can rely on
 * harness", superseding plan 024 grill 6/7's skill-owned/--schema-only stance so
 * `harness flow create flight-plan` works bare at pij dispatch time). The skill
 * stays the single SOURCE; this bundle is a generated copy and `check:flows`
 * guards it against drift. An EMPTY schemas dir is tolerated (warns, emits empty
 * maps) so the pipeline can stand up before the schemas land (T006).
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const schemasDir = join(repoRoot, 'harness/cli/src/services/flow/schemas');
const outPath = join(repoRoot, 'harness/cli/src/services/flow/schemas-content.ts');

/** Collect `*<suffix>` files in the schemas dir → [{ key, parsed }] sorted by name (deterministic). */
function collect(suffix) {
  if (!existsSync(schemasDir)) return [];
  return readdirSync(schemasDir)
    .filter((f) => f.endsWith(suffix))
    .sort()
    .map((f) => {
      const key = f.slice(0, -suffix.length);
      const raw = readFileSync(join(schemasDir, f), 'utf8');
      try {
        return { key, parsed: JSON.parse(raw) };
      } catch (err) {
        throw new Error(`gen-flows: ${f} is not valid JSON: ${err instanceof Error ? err.message : err}`);
      }
    });
}

// Skill-owned types bundled by explicit allowlist (see header). Key = type name;
// value = the skill dir carrying `<type>.schema.json` + `<type>.template.json`.
const SKILL_BUNDLED = { 'flight-plan': 'skills/builder/references' };

/** Collect one allowlisted skill-owned file → { key, parsed } (missing file = hard error: the allowlist is a promise). */
function collectSkill(type, dir, suffix) {
  const path = join(repoRoot, dir, `${type}${suffix}`);
  if (!existsSync(path)) {
    throw new Error(`gen-flows: allowlisted skill bundle source missing: ${path}`);
  }
  try {
    return { key: type, parsed: JSON.parse(readFileSync(path, 'utf8')) };
  } catch (err) {
    throw new Error(
      `gen-flows: ${path} is not valid JSON: ${err instanceof Error ? err.message : err}`,
    );
  }
}

const skillEntries = Object.entries(SKILL_BUNDLED).sort(([a], [b]) => a.localeCompare(b));
const schemas = [
  ...collect('.schema.json'),
  ...skillEntries.map(([type, dir]) => collectSkill(type, dir, '.schema.json')),
];
const templates = [
  ...collect('.template.json'),
  ...skillEntries.map(([type, dir]) => collectSkill(type, dir, '.template.json')),
];

/** Emit `export const <name>: Record<string, unknown> = { … };` from collected entries. */
function emitMap(name, entries) {
  if (entries.length === 0) return `export const ${name}: Record<string, unknown> = {};`;
  const body = entries.map((e) => `  ${JSON.stringify(e.key)}: ${JSON.stringify(e.parsed)},`).join('\n');
  return `export const ${name}: Record<string, unknown> = {\n${body}\n};`;
}

const header = [
  '// @generated by scripts/gen-flows.mjs — DO NOT EDIT.',
  '// Source of truth: harness/cli/src/services/flow/schemas/*.schema.json + *.template.json,',
  '// plus allowlisted skill-owned types (flight-plan ← skills/builder/references/).',
  '// Regenerate with `npm run gen:flows`.',
  '',
].join('\n');

const source = `${header}\n${emitMap('BUNDLED_FLOW_SCHEMAS', schemas)}\n\n${emitMap('BUNDLED_FLOW_TEMPLATES', templates)}\n`;
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, source, 'utf8');

if (schemas.length === 0) {
  console.warn('gen-flows: no *.schema.json found — emitted empty bundle (schemas land in T006).');
}

// Cross-platform biome target (mirrors gen-docs.mjs Finding 05): run the bin .js
// via process.execPath — the node_modules/.bin shim can't execFileSync on Windows.
// Output is byte-identical, so the check:flows drift gate is unaffected.
const biomeBinJs = join(repoRoot, 'node_modules/@biomejs/biome/bin/biome');
if (existsSync(biomeBinJs)) {
  try {
    execFileSync(process.execPath, [biomeBinJs, 'format', '--write', outPath], { stdio: 'ignore' });
  } catch (err) {
    console.warn(
      `gen-flows: biome format failed (${err instanceof Error ? err.message : err}) — run \`npm run fix\`.`,
    );
  }
} else {
  console.warn('gen-flows: biome not found — emitted file may not be biome-canonical (run `npm run fix`).');
}

// stderr, not stdout (gen-docs Finding 01): runs in npm lifecycles where stdout is data.
console.error(
  `gen-flows: wrote ${schemas.length} schemas + ${templates.length} templates → ${outPath.replace(`${repoRoot}/`, '')}`,
);
