#!/usr/bin/env node
/**
 * Build-time docs generator (plan 007, workshop 001 § Option C).
 *
 * Reads the curated allow-list (`docs-manifest.json`) + each source `.md`, and
 * emits a committed TypeScript module (`docs-content.ts`) exporting a `DOCS`
 * array. `tsc` then compiles that into `dist` like any other source file, so the
 * docs ship with the CLI (`files: ["harness/cli/dist"]`) — no runtime fs/path,
 * no asset-copy step, no new `files` entry.
 *
 * Pure Node, zero dependencies. Content is emitted via `JSON.stringify` (never
 * template literals) so backticks, `${`, and newlines in the docs are robustly
 * escaped (KF-06). The output is biome-normalised (when biome is available) so
 * the committed file is lint-clean and byte-stable across regenerations — which
 * is what makes the CI drift check (`git diff --exit-code`) reliable.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const manifestPath = join(repoRoot, 'harness/cli/src/services/docs/docs-manifest.json');
const outPath = join(repoRoot, 'harness/cli/src/services/docs/docs-content.ts');

const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
if (!Array.isArray(manifest.docs) || manifest.docs.length === 0) {
  throw new Error('gen-docs: docs-manifest.json has no `docs` entries.');
}

const rows = manifest.docs.map((entry) => {
  for (const field of ['id', 'title', 'summary', 'audience', 'sourcePath']) {
    if (typeof entry[field] !== 'string' || entry[field].length === 0) {
      throw new Error(`gen-docs: manifest entry missing/invalid "${field}": ${JSON.stringify(entry)}`);
    }
  }
  const srcAbs = join(repoRoot, entry.sourcePath);
  if (!existsSync(srcAbs)) {
    throw new Error(`gen-docs: sourcePath for "${entry.id}" not found: ${entry.sourcePath}`);
  }
  const content = readFileSync(srcAbs, 'utf8');
  return { id: entry.id, title: entry.title, summary: entry.summary, audience: entry.audience, content };
});

const header = [
  '// @generated by scripts/gen-docs.mjs — DO NOT EDIT.',
  '// Source of truth: harness/cli/src/services/docs/docs-manifest.json + the curated .md files.',
  '// Regenerate with `npm run gen:docs`.',
  '',
].join('\n');

const body = rows
  .map((r) =>
    [
      '  {',
      `    id: ${JSON.stringify(r.id)},`,
      `    title: ${JSON.stringify(r.title)},`,
      `    summary: ${JSON.stringify(r.summary)},`,
      `    audience: ${JSON.stringify(r.audience)},`,
      `    content: ${JSON.stringify(r.content)},`,
      '  },',
    ].join('\n'),
  )
  .join('\n');

const source = `${header}\nexport const DOCS = [\n${body}\n] as const;\n`;
writeFileSync(outPath, source, 'utf8');

const biomeBin = join(repoRoot, 'node_modules/.bin/biome');
if (existsSync(biomeBin)) {
  execFileSync(biomeBin, ['format', '--write', outPath], { stdio: 'ignore' });
} else {
  console.warn('gen-docs: biome not found — emitted file may not be biome-canonical (run `npm run fix`).');
}

console.log(`gen-docs: wrote ${rows.length} docs → ${outPath.replace(`${repoRoot}/`, '')}`);
