#!/usr/bin/env node
/**
 * Build-time generator for the baked `harness dd docs` corpus (plan 065, D15).
 *
 * Reads the curated allow-list (`dd-docs-manifest.json`) + each source `.md`, and
 * emits a committed TypeScript module (`docs-content.ts`) exporting a `DD_DOCS`
 * array. `tsc` compiles it into `dist` like any other source file, so the docs
 * ship with the CLI — no runtime fs, no asset-copy step, no new `files` entry.
 *
 * Mirrors `gen-docs.mjs` deliberately: same JSON.stringify escaping (never
 * template literals, so backticks and `${` in the prose are safe), same biome
 * normalisation (so the committed file is byte-stable and the drift check is
 * reliable), same stderr-only logging (stdout is data inside npm lifecycles).
 *
 * Pure Node, zero dependencies. `--check` regenerates and reports drift.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const manifestPath = join(repoRoot, 'harness/cli/src/services/dd/docs/dd-docs-manifest.json');
const outPath = join(repoRoot, 'harness/cli/src/services/dd/docs/docs-content.ts');

const FIELDS = ['id', 'title', 'summary', 'audience', 'sourcePath'];

/**
 * Regenerate `docs-content.ts`. With `check`, compares against the file as it was
 * before the write and reports drift by setting `process.exitCode`.
 */
export function generateDdDocs({ check = false } = {}) {
  const before = existsSync(outPath) ? readFileSync(outPath, 'utf8') : null;
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  if (!Array.isArray(manifest.docs) || manifest.docs.length === 0) {
    throw new Error('gen-dd-docs: dd-docs-manifest.json has no `docs` entries.');
  }

  const rows = manifest.docs.map((entry) => {
    for (const field of FIELDS) {
      if (typeof entry[field] !== 'string' || entry[field].length === 0) {
        throw new Error(
          `gen-dd-docs: manifest entry missing/invalid "${field}": ${JSON.stringify(entry)}`,
        );
      }
    }
    const srcAbs = join(repoRoot, entry.sourcePath);
    if (!existsSync(srcAbs)) {
      throw new Error(`gen-dd-docs: sourcePath for "${entry.id}" not found: ${entry.sourcePath}`);
    }
    return {
      id: entry.id,
      title: entry.title,
      summary: entry.summary,
      audience: entry.audience,
      content: readFileSync(srcAbs, 'utf8'),
    };
  });

  const header = [
    '// @generated by scripts/gen-dd-docs.mjs — DO NOT EDIT.',
    '// Source of truth: harness/cli/src/services/dd/docs/dd-docs-manifest.json + the .md files it names.',
    '// Regenerate with `npm run gen:dd-docs`; `npm run check:dd-docs` fails on drift.',
    // The baked prose quotes real TypeScript, so `${…}` legitimately appears
    // inside these string literals. Suppressed HERE (in the generated artifact)
    // rather than in biome.json, so the escape hatch is scoped to exactly one
    // file and travels with the generator that creates it.
    '// biome-ignore-all lint/suspicious/noTemplateCurlyInString: baked documentation quotes template literals verbatim.',
    '',
  ].join('\n');

  const body = rows
    .map((row) =>
      [
        '  {',
        `    id: ${JSON.stringify(row.id)},`,
        `    title: ${JSON.stringify(row.title)},`,
        `    summary: ${JSON.stringify(row.summary)},`,
        `    audience: ${JSON.stringify(row.audience)},`,
        `    content: ${JSON.stringify(row.content)},`,
        '  },',
      ].join('\n'),
    )
    .join('\n');

  writeFileSync(outPath, `${header}\nexport const DD_DOCS = [\n${body}\n] as const;\n`, 'utf8');

  // Cross-platform biome target (plan 017 Finding 05): the package bin script via
  // process.execPath — node_modules/.bin/biome is a sh shim that cannot
  // execFileSync on Windows. Output is byte-identical, so the drift gate is
  // unaffected; a missing/failing biome warns and never breaks the build.
  const biomeBinJs = join(repoRoot, 'node_modules/@biomejs/biome/bin/biome');
  if (existsSync(biomeBinJs)) {
    try {
      execFileSync(process.execPath, [biomeBinJs, 'format', '--write', outPath], {
        stdio: 'ignore',
      });
    } catch (err) {
      console.warn(
        `gen-dd-docs: biome format failed (${err instanceof Error ? err.message : err}) — run \`npm run fix\`.`,
      );
    }
  } else {
    console.warn('gen-dd-docs: biome not found — emitted file may not be biome-canonical.');
  }

  // stderr, not stdout (plan 017 Finding 01): this runs inside npm lifecycles
  // where stdout is data.
  console.error(`gen-dd-docs: wrote ${rows.length} docs → ${outPath.replace(`${repoRoot}/`, '')}`);

  if (!check) return { drifted: false, count: rows.length };

  const after = readFileSync(outPath, 'utf8');
  if (before === after) {
    console.error('check:dd-docs OK — no drift');
    return { drifted: false, count: rows.length };
  }
  console.error('check:dd-docs FAIL — baked dd docs drifted from their sources; diff follows');
  try {
    execFileSync('git', ['--no-pager', 'diff', '--', outPath], { cwd: repoRoot, stdio: 'inherit' });
  } catch (err) {
    console.error(
      `check:dd-docs: unable to print git diff (${err instanceof Error ? err.message : err})`,
    );
  }
  process.exitCode = 1;
  return { drifted: true, count: rows.length };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  generateDdDocs({ check: process.argv.includes('--check') });
}
