#!/usr/bin/env bash
# new-test-repo.sh — generate a fresh throwaway repo for "real" agent/manual testing.
#
# Creates a minimal repo (package.json with a real `demo` script, a README, and
# `git init`) and prints its absolute path on STDOUT so callers can capture it:
#
#     WORKDIR=$(scripts/new-test-repo.sh)
#     cd "$WORKDIR"
#
# Diagnostics go to STDERR so STDOUT is just the path. Pass an optional [dest]
# to use a specific directory instead of an OS temp dir.
#
# The repo deliberately has NO .harness/ folder — it proves extension-from-zero.
set -euo pipefail

dest="${1:-}"
if [ -z "$dest" ]; then
  dest="$(mktemp -d "${TMPDIR:-/tmp}/harness-test-repo-XXXXXX")"
else
  mkdir -p "$dest"
fi

cat > "$dest/package.json" <<'JSON'
{
  "name": "harness-test-repo",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "description": "Throwaway repo for harness extension testing (generated by scripts/new-test-repo.sh).",
  "scripts": {
    "demo": "node -e \"console.log('demo ok')\""
  }
}
JSON

cat > "$dest/README.md" <<'MD'
# harness test repo (throwaway)

Generated by `scripts/new-test-repo.sh` for real-agent / manual testing of the
harness extension flow. Has a real `npm run demo` script (for `--wrap`) and no
`.harness/` folder, so it proves extension-from-zero.
MD

git -C "$dest" init -q

echo "Created test repo at: $dest" >&2
echo "  install the core:   npm install <path-to-harness-engineering>  (or: npm i github:AI-Substrate/harness-engineering)" >&2
echo "  then:               npx harness doctor  /  npx harness new <verb>" >&2

# STDOUT: just the path (capturable).
echo "$dest"
