// @generated by scripts/gen-flows.mjs — DO NOT EDIT.
// Source of truth: harness/cli/src/services/flow/schemas/*.schema.json + *.template.json.
// Regenerate with `npm run gen:flows`.

export const BUNDLED_FLOW_SCHEMAS: Record<string, unknown> = {
  flow: {
    kind: 'flow-core',
    schema_version: 1,
    description:
      'Shared-core flow contract (plan 024). Defines the universal field shape every flow overlay extends; overlays add `kind` + `statuses` + `nodeTypes`. Hand-rolled validator (flow-schema.ts) — not a JSON-Schema validator doc.',
    node: {
      required: ['id', 'type', 'label', 'status', 'next'],
      optional: [
        'branch_of',
        'created_at',
        'modified_at',
        'ran_at',
        'user_input',
        'comments',
        'authority',
        'agents',
        'output',
        'error',
        'command',
        'chore',
        'note',
        'artifacts',
        'instructions',
        'phase',
        'reconstructed',
        'zone',
        'dd_link',
      ],
    },
    comment: { required: ['at', 'text'], optional: ['source', 'kind', 'refs'] },
    authority: { values: ['cursor', 'substrate'], default: 'cursor' },
    chore: {
      kinds: ['skill', 'command', 'builtin', 'manual'],
      importances: ['strongly-recommended', 'recommended', 'optional', 'informational'],
    },
    root: {
      required: ['schema_version', 'kind', 'slug', 'created_at', 'provenance', 'events', 'nodes'],
      optional: ['nav', 'agents', 'plan_dir', 'mode', 'title', '_comment'],
    },
  },
  'harness-adopt': {
    kind: 'harness-adopt',
    extends: 'flow-core',
    schema_version: 1,
    description:
      "Bundled harness-adopt overlay (plan 032; executes plan 028 §4). The finite 🧰 onboarding flow eng-harness-flow drives once per repo: spine install → governance → build-boot → bridge, with scout + inject as branch_of excursions, terminating at a `bridge` decision (the router's adopt→loop gate; next:[]). Disjoint from harness-loop — detection runs exactly one. Statuses include todo/skipped so a skippable excursion (scout/inject) can be marked skipped without a validator change.",
    statuses: ['assumed', 'known', 'in_progress', 'done', 'blocked', 'todo', 'skipped'],
    nodeTypes: ['install', 'scout', 'governance', 'inject', 'build-boot', 'decision'],
  },
  'harness-loop': {
    kind: 'harness-loop',
    extends: 'flow-core',
    schema_version: 1,
    description:
      'Bundled harness-loop overlay (plan 024 AC-10; driven first-class since plan 032). The cycling ⚙️ engineering loop eng-harness-flow drives — standalone in its own .harness/loop.flow.json — re-entered every coding session: boot → backpressure → observe → drain-gate → retro-drain → retro-harvest → improve. The cycle is a nav RESET, so the graph stays acyclic (improve.next:[]). Disjoint from harness-adopt — detection runs exactly one. `todo`/`skipped` declare the chore lifecycle for the loop-as-chores case (the four fire hooks injected into an active the-flow); the overlay-declared-status path, not a validator change.',
    statuses: ['assumed', 'known', 'in_progress', 'done', 'blocked', 'todo', 'skipped'],
    nodeTypes: ['boot', 'backpressure', 'observe', 'retro', 'improve', 'decision'],
  },
};

export const BUNDLED_FLOW_TEMPLATES: Record<string, unknown> = {
  'harness-adopt': {
    _comment:
      "harness-adopt create-seed (plan 032). The CLI consumes `cursor` (→ nav.now) + `nodes` VERBATIM; root identity (provenance/created_at/events/nav) is stamped by `harness flow create`, so this seed carries none. Build order in the array is spine-first then excursions; zones are explicit because the renderer's ZONE_BY_TYPE has no adopt types (R-3). Boot is built LAST on the spine (028): the moment it exists you run it and cross the bridge into the loop.",
    cursor: 'install',
    nodes: [
      {
        id: 'install',
        type: 'install',
        label: 'Install harness',
        status: 'assumed',
        next: ['governance'],
        zone: 'preflight',
      },
      {
        id: 'governance',
        type: 'governance',
        label: 'Governance + boot contract',
        status: 'assumed',
        next: ['build-boot'],
        zone: 'flight',
      },
      {
        id: 'build-boot',
        type: 'build-boot',
        label: 'Build + run boot (last)',
        status: 'assumed',
        next: ['bridge'],
        zone: 'postflight',
      },
      {
        id: 'bridge',
        type: 'decision',
        label: 'Bridge → harness loop?',
        status: 'assumed',
        next: [],
        zone: 'postflight',
      },
      {
        id: 'scout',
        type: 'scout',
        label: 'Scout (harnessability)',
        status: 'assumed',
        next: ['governance'],
        zone: 'preflight',
        branch_of: 'install',
      },
      {
        id: 'inject',
        type: 'inject',
        label: 'Inject (wire seams)',
        status: 'assumed',
        next: ['build-boot'],
        zone: 'flight',
        branch_of: 'governance',
      },
    ],
  },
  'harness-loop': {
    _comment:
      'harness-loop create-seed (plan 032, modernized from the 024 schema-only stub). The CLI consumes `cursor` (→ nav.now) + `nodes` VERBATIM; root identity (provenance/created_at/events/nav block) is stamped by `harness flow create`. The ⚙️ engineering loop eng-harness-flow drives standalone (own .harness/loop.flow.json) when no the-flow is active. The cycle is modeled as a nav RESET (the driver moves nav.now back to observe/boot) — the DAG stays ACYCLIC (improve.next:[]). retro is split into retro-drain (post-coding) + retro-harvest (post-flight); drain-gate is the decision that orders them. The four fire-hook nodes carry their `command` so the standalone loop is self-documenting; observe/improve/drain-gate fire no hook. Zones are explicit (renderer ZONE_BY_TYPE has no loop types — R-3).',
    cursor: 'boot',
    nodes: [
      {
        id: 'boot',
        type: 'boot',
        label: 'Boot',
        status: 'assumed',
        next: ['backpressure'],
        zone: 'preflight',
        command: 'run /eng-harness-flow --hook pre-flight',
      },
      {
        id: 'backpressure',
        type: 'backpressure',
        label: 'Backpressure Check',
        status: 'assumed',
        next: ['observe'],
        zone: 'preflight',
        command: 'run /eng-harness-flow --hook pre-coding',
      },
      {
        id: 'observe',
        type: 'observe',
        label: 'Do Work + Observe',
        status: 'assumed',
        next: ['drain-gate'],
        zone: 'flight',
      },
      {
        id: 'drain-gate',
        type: 'decision',
        label: 'Buffer non-empty?',
        status: 'assumed',
        next: ['retro-drain', 'retro-harvest'],
        zone: 'flight',
      },
      {
        id: 'retro-drain',
        type: 'retro',
        label: 'Retro — drain buffer',
        status: 'assumed',
        next: ['retro-harvest'],
        zone: 'postflight',
        command: 'run /eng-harness-flow --hook post-coding',
      },
      {
        id: 'retro-harvest',
        type: 'retro',
        label: 'Retro — harvest',
        status: 'assumed',
        next: ['improve'],
        zone: 'postflight',
        command: 'run /eng-harness-flow --hook post-flight',
      },
      {
        id: 'improve',
        type: 'improve',
        label: 'Improve',
        status: 'assumed',
        next: [],
        zone: 'postflight',
      },
    ],
  },
};
