// @generated by scripts/gen-flows.mjs — DO NOT EDIT.
// Source of truth: harness/cli/src/services/flow/schemas/*.schema.json + *.template.json.
// Regenerate with `npm run gen:flows`.

export const BUNDLED_FLOW_SCHEMAS: Record<string, unknown> = {};

export const BUNDLED_FLOW_TEMPLATES: Record<string, unknown> = {};
