import { describe, expect, it } from 'vitest';
import { FakeClock } from '../../../src/adapters/clock/fake-clock.js';
import type { FlowDoc } from '../../../src/services/flow/flow-events.js';
import { applyBatch, setNow, setStatus } from '../../../src/services/flow/flow-mutations.js';
import { renderFlow, renderRailLine } from '../../../src/services/flow/flow-renderer.js';

/**
 * The opt-in contract, regression-pinned (plan 065 P6 T002).
 *
 * Phase 6 put a mechanical refusal into the machinery every flow in every
 * consuming repository already runs on. The mitigation is that the gate is reached
 * only through a node's `dd_link`, and the mitigation is only worth anything if it
 * is PROVEN rather than asserted — so this file states the contract in its
 * strongest available form: with the field absent, the output is byte-identical to
 * running with no gate wired at all.
 *
 * If a future change moves gate evaluation anywhere ahead of the `dd_link` check,
 * this file is what goes red.
 */

const CLOCK = '2026-08-04T09:00:00.000Z';

/** Deps WITH a gate wired that would explode if it were ever consulted. */
function withExplodingGate() {
  return {
    clock: new FakeClock(CLOCK),
    gate: {
      evaluate: () => {
        throw new Error('the gate was evaluated for a flow that carries no dd_link');
      },
    },
  };
}

/** Deps with no gate at all — the pre-Phase-6 world. */
function withoutGate() {
  return { clock: new FakeClock(CLOCK) };
}

function plainFlow(): FlowDoc {
  return {
    schema_version: 1,
    kind: 'harness-loop',
    slug: 'plain',
    nav: { now: 'a', next: null },
    created_at: '2026-08-04T00:00:00.000Z',
    provenance: {
      record_kind: 'flow',
      harness_version: '0.4.0',
      branch: 'main',
      repo: null,
      created_at: '2026-08-04T00:00:00.000Z',
      agent: null,
      plan_id: null,
    },
    events: [],
    nodes: [
      { id: 'a', type: 'boot', label: 'Boot', status: 'done', next: ['b'] },
      { id: 'b', type: 'observe', label: 'Observe', status: 'in_progress', next: ['c'] },
      { id: 'c', type: 'retro', label: 'Retro', status: 'known', next: [] },
    ],
  };
}

/**
 * The EXACT bytes `renderFlow(plainFlow())` must emit — stored, not recomputed.
 *
 * The predecessor of this constant compared `renderFlow(plainFlow())` to
 * `renderFlow(plainFlow())`, which is true for every possible renderer and
 * therefore pinned nothing: it stayed green while the dd-gate legend clause leaked
 * into all five committed goldens. A self-referential assertion is a pin that pins
 * nothing. This is the real pin — every byte a dd-free flow rendered before the
 * gate existed, including a legend that ends at `✕ skipped).` with no `⛨` clause
 * and no shield anywhere in the diagram.
 */
const PLAIN_RENDER = `<!-- GENERATED by \`harness flow render\` — do not hand-edit; regenerate from the flow JSON. -->
# Flow · plain

**Kind**: harness-loop · **Now**: a · **Nodes**: 3 · **Events**: 0

**Rail**: [ ◆─◐ ]─◇  [ ◆ Boot · ◐ Observe ] · ◇ Retro

\`\`\`mermaid
flowchart TD
    a["Boot"]:::done
    b["Observe"]:::harness
    c["Retro"]:::known

    a --> b --> c

    classDef done fill:#1B7F2E,stroke:#0F4F1B,color:#fff;
    classDef known fill:#1E73E8,stroke:#0D3F86,color:#fff;
    classDef harness fill:#7E3FF2,stroke:#4A1FA8,color:#fff;
    classDef current fill:#FF7A00,stroke:#C24E00,color:#1a0e00,stroke-width:4px;
    class a current;
\`\`\`

**Legend** — colour = type/status: 🟩 done · 🟢 in-progress · 🟥 blocked · 🟦 known · ⬜ assumed · 🔶 decision · 🗣 user input · 🟪 harness chore (faded = not yet done) · 🤖 companion · 🛠 worker · 🟧 current (you are here). Badges: 💬 comments · 📄 artifacts · 📝 instructions · 🧰 chore (° optional / recommended / ‼ strongly-recommended; ✓ done · ✕ skipped).
`;

describe('opt-in — a flow without dd_link never reaches the gate', () => {
  it('setNow is byte-identical with and without a gate wired', () => {
    const gated = setNow(plainFlow(), 'b', withExplodingGate());
    const plain = setNow(plainFlow(), 'b', withoutGate());
    expect(gated.ok && plain.ok).toBe(true);
    if (!gated.ok || !plain.ok) return;
    expect(JSON.stringify(gated.doc)).toBe(JSON.stringify(plain.doc));
    expect(gated.notice).toBeUndefined();
  });

  it('--force on an ungated flow changes nothing at all', () => {
    const forced = setNow(plainFlow(), 'b', withExplodingGate(), { force: true });
    const plain = setNow(plainFlow(), 'b', withoutGate());
    expect(forced.ok && plain.ok).toBe(true);
    if (!forced.ok || !plain.ok) return;
    expect(JSON.stringify(forced.doc)).toBe(JSON.stringify(plain.doc));
    expect(forced.notice).toBeUndefined();
  });

  it('every other mutation is untouched by the gate deps', () => {
    const gated = setStatus(plainFlow(), 'b', 'done', withExplodingGate());
    const plain = setStatus(plainFlow(), 'b', 'done', withoutGate());
    expect(gated.ok && plain.ok).toBe(true);
    if (!gated.ok || !plain.ok) return;
    expect(JSON.stringify(gated.doc)).toBe(JSON.stringify(plain.doc));
  });

  it('the render is byte-identical to its stored pre-gate bytes (F006)', () => {
    expect(renderFlow(plainFlow())).toBe(PLAIN_RENDER);
  });

  it('a dd-free render carries no shield and no gate legend clause (F006)', () => {
    const out = renderFlow(plainFlow());
    expect(out).not.toContain('⛨');
    expect(out).not.toContain('dd gate');
    // The legend TERMINATES at the chore clause — opt-in means invisible, and the
    // five committed render goldens are the wider form of this same assertion.
    expect(out.trimEnd().endsWith('✓ done · ✕ skipped).')).toBe(true);
  });

  it('the rail is byte-identical', () => {
    expect(renderRailLine(plainFlow())).toBe('[plain] [ ◆─◐ ]─◇  [ ◆ Boot · ◐ Observe ] · ◇ Retro');
  });
});

describe('opt-in — dd_link round-trips through the mutation surface', () => {
  it('apply --ops can create a node carrying a gate link', () => {
    const result = applyBatch(
      plainFlow(),
      [
        {
          op: 'insert',
          id: 'd',
          type: 'phase',
          label: 'Phase D',
          status: 'known',
          after: 'c',
          dd_link: { address: 'docs/tasks.dd.json#tasks', gate: true },
        },
      ],
      withoutGate(),
    );
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.doc.nodes.at(-1)?.dd_link).toEqual({
      address: 'docs/tasks.dd.json#tasks',
      gate: true,
    });
  });

  it('apply --ops can set a gate link on an existing node', () => {
    const result = applyBatch(
      plainFlow(),
      [{ op: 'set', id: 'b', dd_link: { address: 'docs/tasks.dd.json#tasks' } }],
      withoutGate(),
    );
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.doc.nodes[1]?.dd_link).toEqual({ address: 'docs/tasks.dd.json#tasks' });
    expect(result.doc.events.at(-1)?.details).toMatchObject({ node: 'b', fields: ['dd_link'] });
  });

  it('re-setting the same link is a no-op — no event, no restamp', () => {
    const linked = applyBatch(
      plainFlow(),
      [{ op: 'set', id: 'b', dd_link: { address: 'docs/tasks.dd.json#tasks' } }],
      withoutGate(),
    );
    expect(linked.ok).toBe(true);
    if (!linked.ok) return;
    const again = applyBatch(
      linked.doc,
      [{ op: 'set', id: 'b', dd_link: { address: 'docs/tasks.dd.json#tasks' } }],
      withoutGate(),
    );
    expect(again.ok).toBe(true);
    if (!again.ok) return;
    expect(JSON.stringify(again.doc)).toBe(JSON.stringify(linked.doc));
  });
});
