import {
  lstatSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  renameSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { NodeFs } from '../../../src/adapters/fs/node-fs.js';
import { appendToArray, writeThroughSymlink } from '../../../src/services/hooks/config-writer.js';
import {
  alphabeticalResortWriter,
  deCommentWriter,
  FIXTURES,
  ourCommand,
  readFixture,
  runWriter,
} from '../../support/config-fixture.js';

/**
 * THE COMMENT- AND ORDER-PRESERVING WRITER (plan 082 tk-0002).
 *
 * READ THIS BEFORE TRUSTING THE GOLDEN ROWS. The goldens were GENERATED by this
 * writer and then committed, so "the writer matches the golden" is, on its own,
 * the writer agreeing with itself — the exact defect this plan has now hit seven
 * times. The golden is a REGRESSION LOCK: it catches an unintended change later.
 * The PROOF is the property rows below, each of which is derived from the INPUT and
 * would hold against any correct writer, golden or no golden.
 */

let home: string;
const fs = new NodeFs();

/** Apply the real writer the way an install will. */
const install = (text: string, agent: string): string => {
  const pre = appendToArray(text, {
    path: ['hooks', 'preToolUse'],
    entry: { command: ourCommand(agent, 'pre') },
  });
  return appendToArray(pre, {
    path: ['hooks', 'postToolUse'],
    entry: { command: ourCommand(agent, 'post') },
  });
};

beforeEach(() => {
  home = mkdtempSync(join(tmpdir(), 'harness-config-writer-'));
});
afterEach(() => rmSync(home, { recursive: true, force: true }));

describe('what the writer PRESERVES — derived from the input, not from the golden (dw-0005)', () => {
  it('keeps every comment in a JSONC config', () => {
    const input = readFixture('droid.input.jsonc');
    const comments = input.split('\n').filter((line) => line.trim().startsWith('//'));
    expect(comments.length).toBeGreaterThan(0);

    const produced = install(input, 'droid');
    for (const comment of comments) expect(produced).toContain(comment.trim());
  });

  it('keeps NON-ALPHABETICAL key order', () => {
    /*
    Test Doc:
    - Why: git-ai's serde_json BTreeMap re-sorts every key. `preToolUse` before
      `postToolUse` is the real file's order and the reverse of alphabetical, so a
      re-sorting writer is visible here and nowhere else.
    - Contract: the order in the output is the order in the input.
    */
    for (const fixture of FIXTURES) {
      const input = readFixture(fixture.inputFile);
      const produced = install(input, fixture.agent);
      expect(produced.indexOf('preToolUse')).toBeLessThan(produced.indexOf('postToolUse'));
    }
  });

  it('leaves every byte BEFORE the first edit untouched', () => {
    /*
    Test Doc:
    - Why: this is the property a minimal-edit CST round-trip buys and a
      parse-and-reserialize cannot. It is stronger than "comments survived": it says
      the bytes were never rewritten in the first place.
    - Contract: the document prefix up to the first inserted entry is IDENTICAL.
    */
    const input = readFixture('droid.input.jsonc');
    const produced = install(input, 'droid');
    const prefix = input.slice(0, input.indexOf('"preToolUse"'));

    expect(prefix.length).toBeGreaterThan(50);
    expect(produced.startsWith(prefix)).toBe(true);
  });

  it('keeps the PRE-EXISTING entries, including git-ai\u2019s compound one', () => {
    const input = readFixture('cursor.input.json');
    const produced = install(input, 'cursor');
    expect(produced).toContain('git-ai checkpoint cursor --hook-input stdin');
    expect(produced).toContain('tee -a /tmp/pre.jsonl');
  });

  it('APPENDS rather than replaces — both entries are present afterwards', () => {
    const produced = install(readFixture('cursor.input.json'), 'cursor');
    const doc = JSON.parse(produced) as { hooks: Record<string, { command: string }[]> };
    expect(doc.hooks.preToolUse).toHaveLength(2);
    expect(doc.hooks.postToolUse).toHaveLength(2);
  });

  it('REFORMATS the array it edits — a real cost, stated rather than discovered', () => {
    /*
    Test Doc:
    - Why: "comments and order preserved" is not "byte-identical everywhere". The
      touched array is re-indented to the document's style, so a single-line entry
      becomes multi-line. That is a change to bytes the user wrote.
    - Contract: bounded to the edited array — asserted by the untouched-prefix row
      above, which passes at the same time as this one.
    */
    const input = readFixture('droid.input.jsonc');
    expect(input).toContain('{ "command": "echo droid-pre" }'); // single line in
    const produced = install(input, 'droid');
    expect(produced).not.toContain('{ "command": "echo droid-pre" }'); // multi-line out
    expect(produced).toContain('"command": "echo droid-pre"'); // value intact
  });
});

describe('the writer matches the committed golden — a REGRESSION LOCK, not the proof', () => {
  it.each(FIXTURES)('$agent', (fixture) => {
    expect(install(readFixture(fixture.inputFile), fixture.agent)).toBe(
      readFixture(fixture.goldenFile),
    );
  });

  it('and a parse-and-reserialize writer still FAILS that golden (dw-0006)', () => {
    /*
    Test Doc:
    - Why: dw-0006 asks that a naive implementation cannot pass. The three known-bad
      writers from tk-0001 are re-run against the regenerated goldens, because a
      golden that changed could have quietly stopped rejecting them.
    - Contract: the de-comment and re-sort writers remain RED.
    */
    const droid = FIXTURES.find((f) => f.agent === 'droid');
    if (droid === undefined) throw new Error('droid fixture missing');
    expect(runWriter(home, droid, deCommentWriter).matchesGolden).toBe(false);
    expect(runWriter(home, droid, alphabeticalResortWriter).matchesGolden).toBe(false);
  });
});

describe('writing through a SYMLINKED config path (dw-0007)', () => {
  /**
   * CAN THIS PROCESS CREATE A SYMLINK AT ALL?
   *
   * PROBED, NOT INFERRED FROM `platform()` (plan 083). The question is not "is this
   * Windows" but "does this process hold symlink privilege", and those differ: an
   * elevated Windows box, or one with Developer Mode on, can; an ordinary user
   * account cannot, and `symlinkSync` throws EPERM. Both rows below create a
   * symlink in their SETUP, so on an unelevated Windows host they died before
   * reaching the contract — a staging failure wearing the costume of a product
   * defect.
   *
   * THE PRODUCT IS NOT IMPLICATED AND THESE ROWS ARE NOT WEAKENED. The second one
   * is an executable proof of a real hazard (a rename-based "atomic" write destroys
   * a dotfile-managed config), and a version rewritten to pass without a symlink
   * would prove nothing while looking like it still did. Skipping with a stated
   * reason is the honest answer: the property is unproven on this host, and it says
   * so, rather than reporting a green it did not earn.
   *
   * THIS RAISES THE PINNED SKIP COUNT ON UNELEVATED WINDOWS BY TWO. That is
   * deliberate and must be moved deliberately — `windows.yml` pins the count
   * precisely so "we stopped looking" cannot wear a green.
   */
  const canSymlink = ((): boolean => {
    const dir = mkdtempSync(join(tmpdir(), 'harness-symlink-probe-'));
    try {
      const target = join(dir, 'target');
      writeFileSync(target, 'x', 'utf8');
      symlinkSync(target, join(dir, 'link'));
      return true;
    } catch {
      return false;
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  })();

  const symlinkable = it.skipIf(!canSymlink);
  /**
   * The reason travels in the NAME, so it reaches the JSON reporter and any CI
   * summary. A skipped row whose name does not say WHY is the silence this repo
   * has been bitten by before: someone scanning a run cannot tell a row that was
   * never relevant from a row that could not be attempted on that host.
   */
  const orSkipped = (name: string): string =>
    canSymlink
      ? name
      : `${name} [SKIPPED — this process cannot create a symlink (Windows EPERM without elevation or Developer Mode); the property is NOT proven on this host]`;

  symlinkable(orSkipped('leaves the symlink intact and updates its TARGET'), () => {
    /*
    Test Doc:
    - Why: agent configs are routinely dotfile-managed (chezmoi, stow), so the config
      path is often a symlink into a git-tracked directory. A temp-write + rename —
      the obvious "atomic" write — REPLACES the symlink with a regular file and
      silently detaches the config from its source of truth. Backup does not save us:
      a no-follow backup copies the LINK, not the content.
    - Contract: the path is still a symlink afterwards, and the CONTENT landed in the
      real file.
    - Quality Contribution: asserts BOTH halves. Checking only that the content
      changed would pass for a writer that destroyed the link.
    */
    const store = join(home, 'dotfiles');
    mkdirSync(store, { recursive: true });
    const real = join(store, 'hooks.json');
    writeFileSync(real, '{\n  "hooks": {}\n}\n');

    const linked = join(home, 'hooks.json');
    symlinkSync(real, linked);

    const written = writeThroughSymlink(fs, linked, '{\n  "hooks": { "preToolUse": [] }\n}\n');

    expect(lstatSync(linked).isSymbolicLink()).toBe(true);
    expect(readFileSync(real, 'utf8')).toContain('preToolUse');
    expect(written).toBe(fs.realpath(real));
  });

  symlinkable(
    orSkipped('the RENAME-based atomic write DESTROYS the symlink — the hazard, executable'),
    () => {
      /*
    Test Doc:
    - Why: honesty about what the row above does and does not prove. `writeFileSync`
      already follows a symlink, so a plain write preserves the link on its own —
      the `realpath` call is not load-bearing TODAY. It becomes load-bearing the
      moment someone makes this write atomic, which is exactly what the rest of this
      codebase does (HookStateStore writes temp-then-rename), so it is the obvious
      future "improvement".
    - Contract: demonstrate that temp-write + rename REPLACES the symlink with a
      regular file, while writeThroughSymlink does not.
    - Quality Contribution: converts "a rename would break this" from a comment into
      a measurement, so the guard has a reason a reader can see rather than trust.
    */
      const store = join(home, 'dotfiles2');
      mkdirSync(store, { recursive: true });
      const real = join(store, 'hooks.json');
      writeFileSync(real, '{}\n');
      const linked = join(home, 'linked.json');
      symlinkSync(real, linked);

      // The tempting "atomic" write.
      const temp = `${linked}.tmp`;
      writeFileSync(temp, '{"clobbered":true}\n');
      renameSync(temp, linked);

      expect(lstatSync(linked).isSymbolicLink()).toBe(false); // the link is GONE
      expect(readFileSync(real, 'utf8')).toBe('{}\n'); // the real file never changed

      // Ours, on a fresh link, keeps it.
      rmSync(linked, { force: true });
      symlinkSync(real, linked);
      writeThroughSymlink(fs, linked, '{"ok":true}\n');
      expect(lstatSync(linked).isSymbolicLink()).toBe(true);
      expect(readFileSync(real, 'utf8')).toContain('ok');
    },
  );

  it('writes where asked when the path does not exist yet', () => {
    const target = join(home, 'fresh.json');
    expect(writeThroughSymlink(fs, target, '{}\n')).toBe(target);
    expect(readFileSync(target, 'utf8')).toBe('{}\n');
  });
});

describe('an unparseable config is NOT rewritten', () => {
  it('returns the input unchanged rather than guessing', () => {
    // A config we cannot understand is one we must not touch. Returning the input
    // makes the caller's write a no-op instead of a corruption.
    const broken = '{ this is not json at all';
    expect(appendToArray(broken, { path: ['hooks', 'preToolUse'], entry: { command: 'x' } })).toBe(
      broken,
    );
  });
});
